import test,{mock} from 'node:test';
import assert from 'node:assert/strict';
import {createFakeStore} from './helpers/fake-store.js';
const stores=new Map(),store=n=>{if(!stores.has(n))stores.set(n,createFakeStore());return stores.get(n);};
mock.module('@netlify/blobs',{namedExports:{getStore:store}});
const {registerAccount,signInAccount,finalizeAccount,emailKey}=await import('../netlify/lib/accounts.js');
const {signToken,requireSession}=await import('../netlify/lib/security.js');
const handlers={};for(const name of ['conversations','memory','projects','missions','analytics','connections','status'])handlers[name]=(await import('../netlify/functions/'+name+'.mjs')).default;
const secret='s'.repeat(48),env={get:k=>({SESSION_SECRET:secret,NODE_ENV:'production',ACCESS_CODE:'invite',SAMVIT_KEY_ENCRYPTION_SECRET:'e'.repeat(48),RESEND_API_KEY:'re_fixture',SAMVIT_EMAIL_FROM:'hello@example.test',SAMVIT_PUBLIC_ORIGIN:'https://samvit.test'})[k]};
const request=(path,token,body,method=body?'POST':'GET')=>new Request('https://samvit.test/api/'+path,{method,headers:{cookie:'samvit_session='+token,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});
const tokenFor=a=>signToken(secret,{sub:a.id,version:1,exp:Date.now()+60000});
const registration=async email=>{await registerAccount({email,password:'correct horse battery staple',code:'invite'},env);const index=await store('samvit-accounts').get(await emailKey(email.toLowerCase()),{type:'json'});const a=await store('samvit-accounts').get('account:'+index.id,{type:'json'});await store('samvit-accounts').setJSON('account:'+a.id,{...a,emailVerified:true});return finalizeAccount(store('samvit-accounts'),{...a,emailVerified:true},env);};
test('accounts: registration, duplicate email, wrong password, invitation gate, forged and legacy sessions',async()=>{
 stores.clear();const a=await registration('Owner@example.test');assert.equal(a.email,'owner@example.test');assert.equal(a.role,'owner');assert.match(a.id,/^usr_/);const saved=await store('samvit-accounts').get('account:'+a.id,{type:'json'});assert.equal(saved.password.algorithm,'scrypt');assert.equal(saved.password.N,131072);assert.ok(!JSON.stringify(saved).includes('correct horse'));
 assert.equal((await registration('OWNER@example.test')).id,a.id);await assert.rejects(signInAccount({email:a.email,password:'incorrect password'},env),/incorrect/);await assert.rejects(registerAccount({email:'b@example.test',password:'correct horse battery staple',code:'bad'},env),/invitation/);assert.equal((await signInAccount({email:a.email,password:'correct horse battery staple'},env)).id,a.id);
 const token=await tokenFor(a);assert.equal((await requireSession(request('status',token),env)).accountId,a.id);assert.equal((await requireSession(request('status',token+'x'),env)).status,401);assert.equal((await requireSession(request('status',await signToken(secret,{sub:'samvit-user',exp:Date.now()+60000})),env)).status,401);
});
test('every persisted-record endpoint scopes reads, updates, deletes and direct IDs to its signed-in user',async t=>{
 stores.clear();for(const k of ['SESSION_SECRET','NODE_ENV','ACCESS_CODE','SAMVIT_KEY_ENCRYPTION_SECRET']){const old=process.env[k];process.env[k]=env.get(k);t.after(()=>old===undefined?delete process.env[k]:process.env[k]=old);}
 const a=await registration('a@example.test'),b=await registration('b@example.test'),ta=await tokenFor(a),tb=await tokenFor(b);
 const specs=[['conversations',{messages:[{role:'user',content:'A private note'}]},'conversation','conversations'],['memory',{text:'A private memory'},'memory','memories'],['projects',{name:'Private project'},'project','projects'],['missions',{title:'Private mission',goal:'Private goal',steps:[{title:'First',detail:'Start'}]},'mission','missions']];
 for(const [name,body,singular,plural]of specs){const created=await handlers[name](request(name,ta,body));assert.equal(created.status,201,name+await created.clone().text());const item=(await created.json())[singular];assert.equal((await(await handlers[name](request(name+'?id='+item.id+'&accountId='+a.id,tb))).json())[plural]?.length??0,0);assert.equal((await handlers[name](request(name,tb,{id:item.id,title:'Intrusion',text:'Intrusion',name:'Intrusion'},'PUT'))).status,404,name);await handlers[name](request(name+'?id='+item.id,tb,null,'DELETE'));assert.equal((await(await handlers[name](request(name,ta))).json())[plural].length,1,name);}
 const created=await handlers.connections(request('connections',ta,{action:'save',provider:'openai',name:'Private',model:'gpt-5-mini',apiKey:'test-key-123456',input:1,output:5}));assert.equal(created.status,200,await created.clone().text());const ca=(await(await handlers.connections(request('connections',ta))).json()).connections[0];assert.equal((await(await handlers.connections(request('connections?accountId='+a.id,tb))).json()).connections.length,0);assert.equal((await handlers.connections(request('connections',tb,{action:'save',id:ca.id,provider:'openai',name:'Stolen',model:'gpt-5-mini',apiKey:'test-key-22222'}))).status,400);
 const usage=await(await handlers.analytics(request('analytics?accountId='+a.id,tb))).text();assert.ok(!usage.includes('Private'));const status=await(await handlers.status(request('status?accountId='+a.id,tb))).json();assert.equal(status.account.id,b.id);assert.equal(status.subscription.planId,'free');
});
test('legacy data and subscription migrate only to first owner, retaining originals',async()=>{
 stores.clear();await store('samvit-conversations').setJSON('index',[{id:'old'}]);await store('samvit-conversations').setJSON('convo:old',{id:'old',messages:[]});await store('samvit-subscription').setJSON('sub:samvit-user',{planId:'ultra',status:'active'});const a=await registration('first@example.test'),b=await registration('second@example.test');assert.ok(await store('samvit-conversations').get('accounts/'+a.id+'/convo:old'));assert.equal(await store('samvit-conversations').get('accounts/'+b.id+'/convo:old'),null);assert.ok(await store('samvit-conversations').get('convo:old'));assert.equal((await store('samvit-subscription').get('sub:'+a.id,{type:'json'})).planId,'ultra');assert.equal((await store('samvit-subscription').get('sub:'+b.id,{type:'json'})).planId,'free');
});
