import test,{mock} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHmac} from 'node:crypto';import {createFakeStore} from './helpers/fake-store.js';
const stores=new Map(),store=n=>{if(!stores.has(n))stores.set(n,createFakeStore());return stores.get(n);};let subscriptions=[],stripeCalls=[],stripeFailure=false;
const stripe={subscriptions:{list:async()=>{stripeCalls.push('list');if(stripeFailure)throw Error('Stripe offline');return {data:subscriptions,has_more:false};}},customers:{create:async()=>({id:'cus_owner'})},checkout:{sessions:{create:async args=>{stripeCalls.push(args);return {id:'cs_test',url:'https://checkout.stripe.com/test'};}}},billingPortal:{sessions:{create:async args=>{stripeCalls.push(args);return {url:'https://billing.stripe.com/test'};}}},coupons:{retrieve:async()=>({valid:true,percent_off:30,duration:'forever'})}};
mock.module('@netlify/blobs',{namedExports:{getStore:store}});mock.module('stripe',{defaultExport:class{constructor(){return stripe;}}});
const {reconcileBilling,snapshotSubscription}=await import('../netlify/lib/billing-reconciliation.js');const {ownBillingAccount}=await import('../netlify/lib/billing-ownership.js');const {default:webhook}=await import('../netlify/functions/billing-webhook.mjs');const {default:checkout}=await import('../netlify/functions/billing-create-checkout.mjs');const {default:portal}=await import('../netlify/functions/billing-portal.mjs');const {default:verifyStudent}=await import('../netlify/functions/student-verification-webhook.mjs');const {hasVerifiedStudentEligibility}=await import('../netlify/lib/student-eligibility.js');const {signToken}=await import('../netlify/lib/security.js');
const acacia=JSON.parse(await readFile(new URL('./fixtures/stripe-acacia.json',import.meta.url))),basil=JSON.parse(await readFile(new URL('./fixtures/stripe-basil.json',import.meta.url)));const A='usr_00000000-0000-0000-0000-000000000001',B='usr_00000000-0000-0000-0000-000000000002',secret='x'.repeat(48),map={price_pro:'pro',price_ultra:'ultra'};
const args=(s,event=acacia)=>({store:s,accountId:A,customerId:'cus_owner',event,stripe,priceMap:map});
function configure(t){stores.clear();subscriptions=[];stripeCalls=[];stripeFailure=false;for(const [k,v]of Object.entries({NODE_ENV:'production',DEV_MODE:'false',SESSION_SECRET:secret,SAMVIT_BILLING_ENABLED:'true',STRIPE_SECRET_KEY:'sk_test_example',STRIPE_WEBHOOK_SECRET:secret,STRIPE_PRICE_ID_MAP:JSON.stringify(map),SAMVIT_STUDENT_VERIFIER_SECRET:secret})){const old=process.env[k];process.env[k]=v;t.after(()=>old===undefined?delete process.env[k]:process.env[k]=old);}}
async function seed(){for(const id of [A,B])await store('samvit-accounts').setJSON('account:'+id,{id,sessionVersion:1,emailVerified:true});await store('samvit-users').setJSON('user:'+A,{ownerAccountId:A,stripeCustomerId:'cus_owner'});await store('samvit-billing-customers').setJSON('cus_owner',{accountId:A});}
async function req(path,id=A,body={}){const token=await signToken(secret,{sub:id,version:1,exp:Date.now()+60000});return new Request('https://samvit.test/api/'+path,{method:'POST',headers:{cookie:'samvit_session='+token,'content-type':'application/json'},body:JSON.stringify(body)});}
function signed(body,header='stripe-signature'){const raw=JSON.stringify(body),time=Math.floor(Date.now()/1000),sig=createHmac('sha256',secret).update(time+'.'+raw).digest('hex');return new Request('https://samvit.test/api/webhook',{method:'POST',headers:{[header]:`t=${time},v1=${sig}`},body:raw});}
test('API version fixtures support subscription-level and item-level billing periods',()=>{for(const f of [acacia,basil]){const result=snapshotSubscription(f.data.object,{customerId:'cus_owner',priceMap:map});assert.equal(result.currentPeriodEnd,new Date(1800000000000).toISOString());assert.equal(result.status,'active');}assert.equal(snapshotSubscription(basil.data.object,{customerId:'cus_owner',priceMap:map}).cancelAtPeriodEnd,true);});
test('same-second events reconcile current Stripe state and old deletion cannot cancel switched subscription',async()=>{const s=createFakeStore();subscriptions=[acacia.data.object];await reconcileBilling(args(s));subscriptions=[{...acacia.data.object,status:'canceled'},basil.data.object];await reconcileBilling(args(s,{...acacia,id:'evt_delete_old',type:'customer.subscription.deleted'}));const current=await s.get('sub:'+A,{type:'json'});assert.equal(current.planId,'ultra');assert.equal(current.externalSubscriptionId,'sub_new');subscriptions=[];await reconcileBilling(args(s,{...acacia,id:'evt_older',created:99}));assert.equal((await s.get('sub:'+A,{type:'json'})).planId,'ultra');});
test('lifecycle active, past due, recovery, scheduled cancellation, canceled, resubscription and multiple-subscription denial',async()=>{const s=createFakeStore();let timestamp=101;for(const [status,expected]of [['active','active'],['past_due','past_due'],['active','active'],['canceled','canceled']]){subscriptions=[{...acacia.data.object,status}];const result=await reconcileBilling(args(s,{...acacia,id:'evt_'+timestamp,created:timestamp++}));assert.equal(result.status,expected);}subscriptions=[basil.data.object];assert.equal((await reconcileBilling(args(s,{...basil,created:timestamp++}))).planId,'ultra');subscriptions.push(acacia.data.object);assert.equal((await reconcileBilling(args(s,{...basil,created:timestamp++}))).status,'past_due');});
test('expired reconciliation worker cannot overwrite a newer worker after losing its lease',async()=>{const s=createFakeStore();let clock=1000,release;const held=new Promise(r=>release=r);const slow={subscriptions:{list:async()=>{await held;return {data:[acacia.data.object],has_more:false};}}};const first=reconcileBilling({...args(s),stripe:slow,now:()=>clock});await new Promise(r=>setTimeout(r,20));clock=122000;subscriptions=[basil.data.object];await reconcileBilling({...args(s,basil),now:()=>clock});release();await assert.rejects(first,/lease lost/);assert.equal((await s.get('sub:'+A,{type:'json'})).planId,'ultra');});
test('real webhook validates signatures, reconciles, deduplicates, retries outage, rejects live and ignores checkout success',async t=>{configure(t);await seed();subscriptions=[acacia.data.object];assert.equal((await webhook(signed(acacia))).status,200);assert.equal((await(await webhook(signed(acacia))).json()).duplicate,true);assert.equal((await webhook(signed({...basil,livemode:true}))).status,400);const count=stripeCalls.length;assert.equal((await(await webhook(signed({...acacia,id:'evt_checkout',type:'checkout.session.completed'}))).json()).handled,false);assert.equal(stripeCalls.length,count);stripeFailure=true;assert.equal((await webhook(signed(basil))).status,503);stripeFailure=false;subscriptions=[basil.data.object];assert.equal((await webhook(signed(basil))).status,200);assert.equal((await store('samvit-subscription').get('sub:'+A,{type:'json'})).planId,'ultra');const bad=signed({...acacia,id:'evt_bad'});bad.headers.set('stripe-signature','bad');assert.equal((await webhook(bad)).status,400);});
test('billing ownership never follows client account/customer IDs, blocks forged ownership and live checkout',async t=>{configure(t);await seed();assert.equal((await portal(await req('billing/portal',B,{accountId:A,customerId:'cus_owner'}))).status,503);assert.equal(stripeCalls.length,0);await store('samvit-users').setJSON('user:'+B,{ownerAccountId:A,stripeCustomerId:'cus_owner'});await assert.rejects(ownBillingAccount({accountId:B}),/ownership/);process.env.STRIPE_SECRET_KEY='sk_live_example';assert.equal((await checkout(await req('billing/create-checkout',A,{priceId:'price_pro'}))).status,501);});
test('checkout creates no entitlements and refuses a second active subscription',async t=>{configure(t);await seed();const response=await checkout(await req('billing/create-checkout',A,{priceId:'price_pro',accountId:B,successUrl:'https://evil.test'}));assert.equal(response.status,200);assert.equal(await store('samvit-subscription').get('sub:'+A),null);const payload=stripeCalls.find(x=>typeof x==='object');assert.equal(payload.customer,'cus_owner');assert.equal(new URL(payload.success_url).origin,'https://samvit.test');subscriptions=[acacia.data.object];assert.equal((await checkout(await req('billing/create-checkout',A,{priceId:'price_ultra'}))).status,409);});
test('student verification requires trusted signature, account binding, expiry and monotonic revision',async t=>{configure(t);await seed();const body={accountId:A,status:'verified',expiresAt:Date.now()+86400000,reference:'review_123',verifier:'test-verifier',revision:1};assert.equal((await verifyStudent(signed(body,'x-samvit-verifier-signature'))).status,200);const record=await store('samvit-student-verification').get('student:'+A,{type:'json'});assert.ok(hasVerifiedStudentEligibility(A,record));assert.equal(hasVerifiedStudentEligibility(B,record),false);assert.equal(hasVerifiedStudentEligibility(A,record,record.expiresAt+1),false);assert.equal((await verifyStudent(signed({...body,accountId:B},'x-samvit-verifier-signature'))).status,400);await verifyStudent(signed({...body,status:'revoked',revision:2},'x-samvit-verifier-signature'));await verifyStudent(signed(body,'x-samvit-verifier-signature'));assert.equal((await store('samvit-student-verification').get('student:'+A,{type:'json'})).status,'revoked');});
test('simultaneous checkout clicks create one session and retries reuse it',async t=>{configure(t);await seed();const [a,b]=await Promise.all([checkout(await req('billing/create-checkout',A,{priceId:'price_pro'})),checkout(await req('billing/create-checkout',A,{priceId:'price_pro'}))]);assert.ok([a.status,b.status].includes(200));assert.equal(stripeCalls.filter(x=>typeof x==='object').length,1);const retry=await checkout(await req('billing/create-checkout',A,{priceId:'price_pro'}));assert.equal(retry.status,200);assert.equal(stripeCalls.filter(x=>typeof x==='object').length,1);});
test('a trusted student record alone cannot attach a coupon that is not exactly recurring 30 percent',async t=>{configure(t);await seed();const old=process.env.STRIPE_STUDENT_DISCOUNT_COUPON_ID;process.env.STRIPE_STUDENT_DISCOUNT_COUPON_ID='student30';t.after(()=>old===undefined?delete process.env.STRIPE_STUDENT_DISCOUNT_COUPON_ID:process.env.STRIPE_STUDENT_DISCOUNT_COUPON_ID=old);await store('samvit-student-verification').setJSON('student:'+A,{accountId:A,status:'verified',expiresAt:Date.now()+100000,verifiedAt:Date.now(),reference:'ref',verifier:'service'});const retrieve=stripe.coupons.retrieve;stripe.coupons.retrieve=async()=>({valid:true,percent_off:50,duration:'forever'});try{assert.equal((await checkout(await req('billing/create-checkout',A,{priceId:'price_pro',studentDiscount:true}))).status,503);assert.equal(stripeCalls.filter(x=>typeof x==='object').length,0);}finally{stripe.coupons.retrieve=retrieve;}});
