import test,{mock} from 'node:test';import assert from 'node:assert/strict';import {createFakeStore} from './helpers/fake-store.js';
const stores=new Map(),store=n=>{if(!stores.has(n))stores.set(n,createFakeStore());return stores.get(n);};mock.module('@netlify/blobs',{namedExports:{getStore:store}});
const {registerAccount,signInAccount,emailKey,finalizeAccount}=await import('../netlify/lib/accounts.js'),{issueEmailToken,consumeEmailToken,deliverQueuedEmail}=await import('../netlify/lib/email-channel.js'),{requireSession,signToken}=await import('../netlify/lib/security.js'),{default:authHandler}=await import('../netlify/functions/auth.mjs'),{default:emailHandler}=await import('../netlify/functions/email.mjs');
const vars={NODE_ENV:'production',SESSION_SECRET:'s'.repeat(48),SAMVIT_KEY_ENCRYPTION_SECRET:'e'.repeat(48),RESEND_API_KEY:'re_fixture',SAMVIT_EMAIL_FROM:'hello@example.test',SAMVIT_PUBLIC_ORIGIN:'https://samvit.test',SAMVIT_OWNER_CLAIM_SECRET:'operator-claim-secret-123'},env={get:k=>vars[k]},password='correct horse battery staple';
const req=(path,body)=>new Request('https://samvit.test/api/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
async function registered(email='person@example.test'){await registerAccount({email,password,code:vars.SAMVIT_OWNER_CLAIM_SECRET},env);const index=await store('samvit-accounts').get(await emailKey(email),{type:'json'});return store('samvit-accounts').get('account:'+index.id,{type:'json'});}
function configure(t){stores.clear();for(const [k,v]of Object.entries(vars)){const old=process.env[k];process.env[k]=v;t.after(()=>old===undefined?delete process.env[k]:process.env[k]=old);}}
test('existing and new registration/reset requests have identical status, body and no authentication cookie',async t=>{configure(t);const a=await authHandler(req('auth',{action:'register',email:'person@example.test',password,code:vars.SAMVIT_OWNER_CLAIM_SECRET}),{}),b=await authHandler(req('auth',{action:'register',email:'person@example.test',password,code:vars.SAMVIT_OWNER_CLAIM_SECRET}),{});assert.equal(a.status,202);assert.equal(b.status,a.status);assert.equal(await a.text(),await b.text());assert.equal(a.headers.get('set-cookie'),null);store('samvit-ratelimits')._data.clear();store('samvit-ratelimits')._metadata.clear();const one=await emailHandler(req('email',{action:'reset',email:'person@example.test'}),{}),two=await emailHandler(req('email',{action:'reset',email:'absent@example.test'}),{});assert.equal(one.status,two.status);assert.equal(await one.text(),await two.text());assert.equal(stores.get('samvit-email-outbox')._data.size,4);});
test('unverified sign-in works but cannot claim ownership or spend through protected endpoints',async()=>{stores.clear();const a=await registered();const signin=await signInAccount({email:a.email,password},env);assert.equal(signin.emailVerified,false);assert.equal(await store('samvit-accounts').get('meta'),null);const token=await signToken(vars.SESSION_SECRET,{sub:a.id,version:1,exp:Date.now()+60000});for(const path of ['chat','agents','billing/create-checkout','connections']){const response=await requireSession(new Request('https://samvit.test/api/'+path,{headers:{cookie:'samvit_session='+token}}),env);assert.equal(response.ok,false,path);assert.equal(response.status,403);}assert.equal((await requireSession(new Request('https://samvit.test/api/auth',{headers:{cookie:'samvit_session='+token}}),env)).ok,true);const verified=await consumeEmailToken(await issueEmailToken(a.id,'verify'),'verify','my new verified password');await finalizeAccount(store('samvit-accounts'),verified,env);assert.equal((await store('samvit-accounts').get('meta',{type:'json'})).ownerAccountId,a.id);});
test('reset links expire, consume once under concurrency and revoke sessions',async()=>{stores.clear();const a=await registered();const expired=await issueEmailToken(a.id,'reset',1000);await assert.rejects(consumeEmailToken(expired,'reset','a newly chosen password',1801001),/expired/);const token=await issueEmailToken(a.id,'reset');const results=await Promise.allSettled([consumeEmailToken(token,'reset','a newly chosen password'),consumeEmailToken(token,'reset','a newly chosen password')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await store('samvit-accounts').get('account:'+a.id,{type:'json'})).sessionVersion,2);await assert.rejects(consumeEmailToken(token,'reset','a newly chosen password'),/expired/);});
test('email missing configuration fails closed, provider failure is recorded rather than sent',async t=>{configure(t);delete process.env.RESEND_API_KEY;const response=await emailHandler(req('email',{action:'reset',email:'any@example.test'}),{});assert.equal(response.status,503);assert.match(await response.text(),/not configured/);const a=await registered();const job=JSON.parse([...store('samvit-email-outbox')._data.values()][0]);assert.equal(await deliverQueuedEmail(job,env,{fetcher:async()=>new Response('',{status:401})}),false);const failed=await store('samvit-email-outbox').get(job.id,{type:'json'});assert.equal(failed.status,'failed');assert.ok(!JSON.stringify(failed).includes(a.email));});
test('real email adapter sends only to configured service, with stable idempotency and trusted-origin link',async()=>{stores.clear();await registered();const job=JSON.parse([...store('samvit-email-outbox')._data.values()][0]);let sent;assert.equal(await deliverQueuedEmail(job,env,{fetcher:async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');assert.equal(options.headers['idempotency-key'],'samvit-email-'+job.id);sent=JSON.parse(options.body);return Response.json({id:'resend-test-message'});}}),true);assert.ok(sent.text.includes('https://samvit.test/#email?'));assert.equal((await store('samvit-email-outbox').get(job.id,{type:'json'})).delivery,null);});
