import test,{mock} from 'node:test';import assert from 'node:assert/strict';import {createFakeStore} from './helpers/fake-store.js';
const stores=new Map(),store=n=>{if(!stores.has(n))stores.set(n,createFakeStore());return stores.get(n);};mock.module('@netlify/blobs',{namedExports:{getStore:store}});
const {registerAccount,signInAccount,emailKey}=await import('../netlify/lib/accounts.js'),{issueEmailToken,consumeEmailToken,deliverQueuedEmail,acceptedEmail}=await import('../netlify/lib/email-channel.js'),{requireSession,signToken}=await import('../netlify/lib/security.js'),{default:authHandler}=await import('../netlify/functions/auth.mjs'),{default:emailHandler}=await import('../netlify/functions/email.mjs');
const vars={NODE_ENV:'production',SESSION_SECRET:'s'.repeat(48),SAMVIT_KEY_ENCRYPTION_SECRET:'e'.repeat(48),RESEND_API_KEY:'re_fixture',SAMVIT_EMAIL_FROM:'hello@example.test',SAMVIT_PUBLIC_ORIGIN:'https://samvit.test'},env={get:k=>vars[k]},password='correct horse battery staple';
const req=(path,body)=>new Request('https://samvit.test/api/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
async function registered(email='person@example.test'){const r=await registerAccount({email,password},env);return store('samvit-accounts').get('account:'+r.id,{type:'json'});}
function configure(t){stores.clear();for(const [k,v]of Object.entries(vars)){const old=process.env[k];process.env[k]=v;t.after(()=>old===undefined?delete process.env[k]:process.env[k]=old);}}
test('V14: existing and new registration/reset requests have identical status, body and no authentication cookie',async t=>{configure(t);const a=await authHandler(req('auth',{action:'register',email:'person@example.test',password}),{}),b=await authHandler(req('auth',{action:'register',email:'person@example.test',password}),{});assert.equal(a.status,202);assert.equal(b.status,a.status);assert.equal(await a.text(),await b.text());assert.equal(a.headers.get('set-cookie'),null);store('samvit-ratelimits')._data.clear();store('samvit-ratelimits')._metadata.clear();const one=await emailHandler(req('email',{action:'reset',email:'person@example.test'}),{}),two=await emailHandler(req('email',{action:'reset',email:'absent@example.test'}),{});assert.equal(one.status,two.status);assert.equal(await one.text(),await two.text());
 // One register email queued (the duplicate is inside the 60s resend
 // cooldown and suppresses silently — acceptance shape is unchanged), plus
 // the two resets. No secret appears anywhere in the outbox.
 assert.equal(stores.get('samvit-email-outbox')._data.size,3);
 assert.ok(!JSON.stringify([...stores.get('samvit-email-outbox')._data.values()]).includes(password));});
test('V14: resend cooldown is per-account and silent; daily cap holds',async t=>{configure(t);await registerAccount({email:'cool@example.test',password},env);const first=await emailHandler(req('email',{action:'verify',email:'cool@example.test'}),{}),second=await emailHandler(req('email',{action:'verify',email:'cool@example.test'}),{});assert.equal(first.status,202);assert.deepEqual(await second.json(),acceptedEmail);assert.equal(stores.get('samvit-email-outbox')._data.size,1);});
test('V14: unverified sign-in is refused; protected endpoints deny unverified sessions; verification activates',async()=>{stores.clear();const a=await registered();await assert.rejects(signInAccount({email:a.email,password},env),err=>{assert.equal(err.status,403);assert.equal(err.needsVerification,true);return true;});
 // A session minted before verification is gated server-side on every
 // protected path regardless of the client it claims to be.
 const token=await signToken(vars.SESSION_SECRET,{sub:a.id,version:1,exp:Date.now()+60000});
 for(const path of ['chat','agents','billing/create-checkout','connections']){const response=await requireSession(new Request('https://samvit.test/api/'+path,{headers:{cookie:'samvit_session='+token}}),env);assert.equal(response.ok,false,path);assert.equal(response.status,403,path);}
 assert.equal((await requireSession(new Request('https://samvit.test/api/auth',{headers:{cookie:'samvit_session='+token}}),env)).ok,true);
 await consumeEmailToken(await issueEmailToken(a.id,'verify'),'verify',{});
 assert.equal((await store('samvit-accounts').get('account:'+a.id,{type:'json'})).emailVerified,true);
 assert.equal((await store('samvit-accounts').get('meta',{type:'json'})),null);});
test('V14: reset links expire, consume once under concurrency, require a new password and revoke sessions',async()=>{stores.clear();const a=await registered();const expired=await issueEmailToken(a.id,'reset',1000);await assert.rejects(consumeEmailToken(expired,'reset',{newPassword:'a newly chosen password',now:1801001}),/expired/);await assert.rejects(issueEmailToken(a.id,'reset').then(t=>consumeEmailToken(t,'reset',{})),/password/i);const token=await issueEmailToken(a.id,'reset');const results=await Promise.allSettled([consumeEmailToken(token,'reset',{newPassword:'a newly chosen password'}),consumeEmailToken(token,'reset',{newPassword:'a newly chosen password'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await store('samvit-accounts').get('account:'+a.id,{type:'json'})).sessionVersion,2);await assert.rejects(consumeEmailToken(token,'reset',{newPassword:'a newly chosen password'}),/expired/);});
test('V14: verify kind needs no password; enable re-activates a disabled account with a new password',async()=>{stores.clear();const a=await registered();
 const verified=await consumeEmailToken(await issueEmailToken(a.id,'verify'),'verify',{});
 assert.equal(verified.emailVerified,true);
 assert.equal((await signInAccount({email:a.email,password},env)).id,a.id); // password untouched
 await store('samvit-accounts').setJSON('account:'+a.id,{...verified,disabled:true,sessionVersion:verified.sessionVersion});
 const enabled=await consumeEmailToken(await issueEmailToken(a.id,'enable'),'enable',{newPassword:'a second strong password'});
 assert.equal(enabled.disabled,false);
 await assert.rejects(signInAccount({email:a.email,password},env),/incorrect/);});
test('V14: email missing configuration fails closed, provider failure is recorded rather than sent',async t=>{configure(t);delete process.env.RESEND_API_KEY;const response=await emailHandler(req('email',{action:'reset',email:'any@example.test'}),{});assert.equal(response.status,503);assert.match(await response.text(),/not configured/);process.env.RESEND_API_KEY=vars.RESEND_API_KEY;const a=await registered();await emailHandler(req('email',{action:'reset',email:a.email}),{});const job=JSON.parse([...store('samvit-email-outbox')._data.values()][0]);assert.equal(await deliverQueuedEmail(job,env,{fetcher:async()=>new Response('',{status:401})}),false);const failed=await store('samvit-email-outbox').get(job.id,{type:'json'});assert.equal(failed.status,'failed');assert.ok(!JSON.stringify(failed).includes(a.email));assert.ok(!JSON.stringify(failed).includes(password));});
test('V14: real email adapter sends only to configured service, with stable idempotency and trusted-origin link',async()=>{stores.clear();const a=await registered();await store('samvit-email-outbox').setJSON('job-register',{id:'job-register',accountId:a.id,payload:await (async()=>{const {sealKey}=await import('../netlify/lib/connection-store.js');return sealKey(JSON.stringify({to:a.email,accountId:a.id,kind:'register'}),env,'email:job-register');})(),status:'pending',attempts:0,createdAt:Date.now()});const job=JSON.parse(store('samvit-email-outbox')._data.get('job-register'));let sent;assert.equal(await deliverQueuedEmail(job,env,{fetcher:async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');assert.equal(options.headers['idempotency-key'],'samvit-email-'+job.id);sent=JSON.parse(options.body);return Response.json({id:'resend-test-message'});}}),true);assert.ok(sent.text.includes('https://samvit.test/#email?'));assert.equal(sent.to[0],a.email);assert.equal((await store('samvit-email-outbox').get(job.id,{type:'json'})).payload,null);});
