import test,{mock} from 'node:test';import assert from 'node:assert/strict';import {createFakeStore} from './helpers/fake-store.js';
const stores=new Map(),store=n=>{if(!stores.has(n))stores.set(n,createFakeStore());return stores.get(n);};mock.module('@netlify/blobs',{namedExports:{getStore:store}});
const {classifyTask,validatePlan,analyzeAndPlan,readyTasks}=await import('../netlify/lib/intelligence/planning.js');
const {calculate}=await import('../netlify/lib/intelligence/calculator.js');const {nativeRequest,parseNative,nativeCompletion}=await import('../netlify/lib/intelligence/native.js');
const {executeTool,registerTool}=await import('../netlify/lib/intelligence/tools.js');const {publicURL,publicIPv4,safeFetch}=await import('../netlify/lib/intelligence/safe-fetch.js');
const {runAgent}=await import('../netlify/lib/intelligence/agent.js');const {rankContext,saveResource,resources,memoryContext}=await import('../netlify/lib/intelligence/context.js');
const {verifyClaims,verifyCalculation}=await import('../netlify/lib/intelligence/verification.js');const {createJob,getJob,commandJob,jobKey,JOB_STORE}=await import('../netlify/lib/intelligence/jobs.js');const {runJob}=await import('../netlify/lib/intelligence/runtime.js');
const A='usr_00000000-0000-0000-0000-000000000001',B='usr_00000000-0000-0000-0000-000000000002',env={get:()=>undefined};
const context=()=>({accountId:A,env,signal:new AbortController().signal,grants:['calculate'],confirmed:[],resourceIds:[],projectId:null,effectId:'output-1',assertActive:async()=>{},consumeTool:async()=>{},reserveCall:async()=>{},trace:async()=>{},limits:{maxAgentSteps:3},goal:'Test task',jobId:crypto.randomUUID()});
const task=(id,dependencies=[],kind='work')=>({id,description:'Complete '+id,dependencies,kind,capability:'general',tools:[]});
const spec={intent:'analyze',complexity:'complex',freshness_required:false,needs_tools:false,needs_verification:true,risk:'low',output_type:'report',strategy:'critique'};
const plan={tasks:[task('research'),task('check',['research'],'verify'),task('final',['check'],'synthesis')]};
const report={claims:[{claim:'A supported calculation',status:'supported',sourceUrls:[],note:'Reviewed model output'}],summary:'Review',confidence:'medium',pipeline_stage:'verified'};
async function seed(){stores.clear();for(const id of [A,B]){await store('samvit-accounts').setJSON('account:'+id,{id,emailVerified:true,sessionVersion:1});await store('samvit-subscription').setJSON('sub:'+id,{planId:'pro',status:'active'});}}
test('router separates cheap arithmetic, ambiguous, current and consequential tasks',()=>{assert.equal(classifyTask('What is 2+2?').calculation.result,4);assert.equal(classifyTask('Explain gravity').analyze,false);assert.equal(classifyTask('Investigate competing hypotheses and design an experiment').analyze,true);assert.equal(classifyTask('current company prices').freshness_required,true);assert.equal(classifyTask('Send this report to everyone').risk,'high');});
test('calculator refuses arbitrary code, infinite and malformed expressions',()=>{assert.equal(calculate('(8+2)*3').result,30);for(const s of ['process.env','1/0','2 2+2','Math.random()','1e999+1'])assert.throws(()=>calculate(s));assert.equal(verifyCalculation('2+2',5).status,'conflict');});
test('DAG validation rejects cycles, unknown dependencies, duplicate IDs, unavailable tools and missing synthesis',()=>{assert.equal(validatePlan(plan).tasks.length,3);for(const bad of [{tasks:[task('a',['b']),task('b',['a'])]},{tasks:[task('a',['missing'])]},{tasks:[task('a'),task('a')]},{tasks:[{...task('a'),tools:['shell']}]},{tasks:[task('a'),task('b',['a'])]}])assert.throws(()=>validatePlan(bad));const ready=readyTasks([{...task('a'),status:'pending'},{...task('b'),status:'pending'},{...task('c',['a','b'],'synthesis'),status:'pending'}],2);assert.deepEqual(ready.map(x=>x.id),['a','b']);});
test('intelligent analyzer and planner consume model JSON; freshness cannot be downgraded',async()=>{let calls=0;const result=await analyzeAndPlan('Compare alternative engineering designs',{complete:async()=>JSON.stringify(++calls===1?spec:plan),toolNames:[],limits:{maxTasks:8,maxParallel:2}});assert.equal(calls,2);assert.equal(result.plan.tasks.length,3);await assert.rejects(analyzeAndPlan('Research current prices',{complete:async()=>JSON.stringify(spec),toolNames:[],limits:{maxTasks:8,maxParallel:2}}),/Current information/);});
test('native OpenAI/Anthropic/Gemini/xAI tool responses normalize without hidden reasoning',()=>{
 const call={id:'c1',name:'calculate',arguments:{expression:'2+2'}};
 const open={choices:[{finish_reason:'tool_calls',message:{content:null,reasoning_content:'hidden',tool_calls:[{id:'c1',function:{name:'calculate',arguments:'{"expression":"2+2"}'}}]}}],usage:{prompt_tokens:10,completion_tokens:5}};
 assert.deepEqual(parseNative('openai',open).calls,[call]);assert.deepEqual(parseNative('grok',open).calls,[call]);
 const claude=parseNative('claude',{stop_reason:'tool_use',content:[{type:'thinking',thinking:'hidden'},{type:'tool_use',id:'c1',name:'calculate',input:call.arguments}],usage:{input_tokens:10,output_tokens:5}});assert.equal(JSON.stringify(claude).includes('hidden'),false);
 const gemini=parseNative('gemini',{candidates:[{finishReason:'STOP',content:{parts:[{thought:true,text:'hidden'},{functionCall:{id:'c1',name:'calculate',args:call.arguments},thoughtSignature:'opaque-signature'}]}}],usageMetadata:{promptTokenCount:10,candidatesTokenCount:4,thoughtsTokenCount:1}});assert.equal(gemini.native[0].thoughtSignature,'opaque-signature');assert.equal(gemini.usage.outputTokens,5);
 for(const provider of ['openai','claude','gemini','grok']){const request=nativeRequest(provider,'fixture-key',{model:'fixture',system:'Policy',history:[{role:'user',content:'2+2'}],tools:[{name:'calculate',description:'Arithmetic',inputSchema:{type:'object',properties:{}}}],env,maxTokens:10});assert.ok(JSON.parse(request.body).tools);assert.ok(!request.url.includes('streamGenerateContent'));}
 assert.throws(()=>parseNative('openai',{choices:[{finish_reason:'content_filter',message:{}}]}),/declined/);
});
test('native wire fails explicitly for invalid JSON, safety and unsupported requests',async()=>{const p={model:'fixture',history:[{role:'user',content:'hi'}],system:'Policy',env,signal:new AbortController().signal};await assert.rejects(nativeCompletion('openai','key',p,{fetcher:async()=>new Response('oops')}),/invalid JSON/);await assert.rejects(nativeCompletion('openai','key',p,{fetcher:async()=>Response.json({error:{}},{status:400})}),e=>e.reason==='unsupported'&&e.rejected);});
test('tool schemas, authorization, private resources and arbitrary actions are enforced independently of model instructions',async()=>{await seed();const ctx=context();assert.equal(JSON.parse((await executeTool({name:'calculate',arguments:{expression:'2+2'}},ctx)).text).result,4);await assert.rejects(executeTool({name:'calculate',arguments:{expression:'2+2',permission:'approved'}},ctx),/unexpected/);await assert.rejects(executeTool({name:'fetch_url',arguments:{url:'https://example.com'}},ctx),/permission/);await assert.rejects(executeTool({name:'shell',arguments:{command:'echo secret'}},ctx),/unavailable/);await saveResource(A,{id:'private',name:'note.txt',content:'private A'});await assert.rejects(executeTool({name:'file_read',arguments:{id:'private'}},{...ctx,accountId:B,grants:['file_read'],resourceIds:['private']}),/unavailable/);await assert.rejects(saveResource(A,{id:'x',name:'../../secret',content:'x'}),/Invalid/);});
test('medium-risk artifact creation requires explicit server-recorded confirmation and is idempotent',async()=>{await seed();const ctx={...context(),grants:['create_document']},call={name:'create_document',arguments:{name:'report',format:'markdown',content:'# Result'}};await assert.rejects(executeTool(call,ctx),/permission/);ctx.confirmed=['create_document'];await executeTool(call,ctx);await executeTool(call,ctx);assert.equal((await resources(A)).length,1);});
test('URL fetch rejects private, encoded, reserved, credential and redirect-capable schemes before a socket opens',async()=>{for(const u of ['http://example.com','https://127.1','https://2130706433','https://169.254.169.254','https://[::1]','https://user:pass@example.com','file:///tmp/a','https://example.com:8080'])assert.throws(()=>publicURL(u),u);for(const ip of ['10.0.0.1','100.64.0.1','198.18.0.1','224.0.0.1'])assert.equal(publicIPv4(ip),false);let opened=false;await assert.rejects(safeFetch('https://example.com',{resolver:async()=>[{address:'10.0.0.1'}],request:()=>{opened=true;}}),/private/);assert.equal(opened,false);assert.equal(publicIPv4('8.8.8.8'),true);});
test('tool timeout aborts bounded work',async()=>{registerTool({name:'test_timeout',description:'test',risk:'low',permissions:['test_timeout'],requiresAuth:true,confirmationRequired:false,inputSchema:{type:'object',properties:{}},outputSchema:{type:'object',properties:{text:{type:'string'}},required:['text']},available:()=>true,costUsd:0,timeoutMs:5,handler:async()=>new Promise(()=>{})});await assert.rejects(executeTool({name:'test_timeout',arguments:{}},{...context(),grants:['test_timeout']}),/timed out/);});
test('agent observes real tool result, rejects injected tools, and stops at loop/cancellation limits',async()=>{const ctx=context(),t={...task('a'),tools:['calculate']};let count=0;const out=await runAgent(ctx,t,{}, {modelCall:async(_ctx,args)=>{if(++count===1)return {content:'',calls:[{id:'c',name:'calculate',arguments:{expression:'2+2'}}],target:'fixture'};assert.match(args.history.at(-1).content,/"result":4/);return {content:'4',calls:[],target:'fixture'};}});assert.equal(out.output,'4');await assert.rejects(runAgent(ctx,t,{}, {modelCall:async()=>({content:'',calls:[{id:'c',name:'unapproved_publish',arguments:{}}],target:'fixture'})}),/step limit/);const c=new AbortController();c.abort();await assert.rejects(runAgent({...ctx,signal:c.signal},t,{}, {modelCall:async()=>assert.fail()}));});
test('verification downgrades invented citations and disagreements, never claims independent proof',()=>{const evidence=[{url:'https://example.com',text:'A',retrievedAt:1}],r=verifyClaims({claims:[{claim:'A',status:'supported',sourceUrls:['https://invented.test'],note:''},{claim:'B',status:'conflict',sourceUrls:[],note:'disagreement'}],summary:'Review',confidence:'high',pipeline_stage:'verified'},evidence,{freshness:true});assert.equal(r.confidence,'low');assert.equal(r.status,'unresolved');assert.equal(r.independentlyProven,false);});
test('memory ranks bounded relevant records while excluding archived and unrelated projects',async()=>{await seed();const rows=[{id:'a',projectId:'p1',content:'telescope astronomy',pinned:true},{id:'b',projectId:'p2',content:'astronomy'},{id:'c',projectId:'p1',content:'astronomy',archived:true}];assert.deepEqual(rankContext(rows,'astronomy',{projectId:'p1'}).map(x=>x.id),['a']);assert.equal((await memoryContext(B,null,'anything')).length,0);});
test('job creation deduplicates and enforces per-account admission and resource isolation',async()=>{await seed();const id=crypto.randomUUID(),body={requestId:id,goal:'Explain gravity'};const [a,b]=await Promise.all([createJob(A,body,env),createJob(A,body,env)]);assert.equal(a.id,b.id);assert.equal(await getJob(B,id),null);await assert.rejects(createJob(A,{...body,goal:'Different goal'},env),/different goal/);await createJob(A,{...body,requestId:crypto.randomUUID()},env);await createJob(A,{...body,requestId:crypto.randomUUID()},env);await assert.rejects(createJob(A,{...body,requestId:crypto.randomUUID()},env),/existing mission/);});
test('exact arithmetic bypasses model calls and concurrent workers do not duplicate work',async()=>{await seed();const job=await createJob(A,{requestId:crypto.randomUUID(),goal:'What is 2+2?'},env);const results=await Promise.all([runJob(A,job.id,env,{modelCall:async()=>assert.fail('no model needed')}),runJob(A,job.id,env,{modelCall:async()=>assert.fail()})]);assert.equal(results.filter(r=>r.claimed).length,1);const saved=await getJob(A,job.id);assert.equal(saved.output,'4');assert.equal(saved.modelCalls,0);assert.equal(saved.status,'completed');});
test('durable DAG executes dependencies, verifier and synthesis; traces have no reasoning field',async()=>{await seed();const job=await createJob(A,{requestId:crypto.randomUUID(),goal:'Compare alternative engineering designs'},env);let stage=0;await runJob(A,job.id,env,{modelCall:async()=>({content:JSON.stringify(++stage===1?spec:plan)}),agent:async(ctx,t)=>{await ctx.reserveCall(10);return {output:t.kind==='verify'?JSON.stringify(report):'Deliverable '+t.id,evidence:[],models:['fixture'],steps:1};}});const saved=await getJob(A,job.id);assert.equal(saved.status,'completed');assert.equal(saved.tasks.length,3);assert.equal(saved.output,'Deliverable final');assert.equal(saved.spentMicroUsd,30);assert.ok(saved.tasks.every(t=>t.status==='completed'));assert.equal(JSON.stringify(saved.trace).includes('chain_of_thought'),false);});
test('pause/cancel persist across worker responses and invalidated accounts stop execution',async()=>{await seed();const job=await createJob(A,{requestId:crypto.randomUUID(),goal:'Explain gravity'},env);await commandJob(A,job.id,'pause');assert.equal((await runJob(A,job.id,env)).claimed,false);await commandJob(A,job.id,'resume');await store('samvit-accounts').setJSON('account:'+A,{id:A,emailVerified:true,sessionVersion:2});await runJob(A,job.id,env,{modelCall:async()=>assert.fail()});assert.equal((await getJob(A,job.id)).status,'failed');await commandJob(A,job.id,'cancel');});
