import test,{mock} from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import {createFakeStore} from './helpers/fake-store.js';
const stores=new Map(),store=n=>{if(!stores.has(n))stores.set(n,createFakeStore());return stores.get(n);};mock.module('@netlify/blobs',{namedExports:{getStore:store}});
const {hashPassword}=await import('../netlify/lib/passwords.js'),{changeAccount,requestAccountDeletion,purgeAccount}=await import('../netlify/lib/account-lifecycle.js'),{emailKey}=await import('../netlify/lib/accounts.js'),{signToken,requireSession}=await import('../netlify/lib/security.js'),{default:accountHandler}=await import('../netlify/functions/account.mjs'),{STORE_INVENTORY,PERSONAL_STORES}=await import('../netlify/lib/store-inventory.js');
const A='usr_00000000-0000-0000-0000-000000000001',B='usr_00000000-0000-0000-0000-000000000002',secret='s'.repeat(48),password='correct horse battery staple';const env={get:k=>({SESSION_SECRET:secret,NODE_ENV:'production'})[k]};
async function seed(){stores.clear();const a={id:A,email:'a@example.test',password:await hashPassword(password),sessionVersion:1,disabled:false,emailVerified:true};await store('samvit-accounts').setJSON('account:'+A,a);await store('samvit-accounts').setJSON(await emailKey(a.email),{id:A});return a;}
const token=v=>signToken(secret,{sub:A,version:v,exp:Date.now()+60000});const request=(t,body)=>new Request('https://samvit.test/api/account',{method:body?'POST':'GET',headers:{cookie:'samvit_session='+t,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});
test('password change renews caller cookie and revokes a second device; signout-all kills every session',async t=>{await seed();for(const k of ['SESSION_SECRET','NODE_ENV']){const old=process.env[k];process.env[k]=env.get(k);t.after(()=>old===undefined?delete process.env[k]:process.env[k]=old);}const before=await token(1);const response=await accountHandler(request(before,{action:'password',currentPassword:password,newPassword:'a different strong password'}),{});assert.equal(response.status,200);const fresh=decodeURIComponent(response.headers.get('set-cookie').split(';')[0].split('=')[1]);assert.equal((await requireSession(request(before),env)).ok,false);assert.equal((await requireSession(request(fresh),env)).ok,true);await changeAccount(A,'signout-all',{});assert.equal((await requireSession(request(fresh),env)).ok,false);});
test('disabled accounts are denied immediately; re-enable requires password and changes session version',async()=>{await seed();await changeAccount(A,'disable',{currentPassword:password});assert.equal((await requireSession(request(await token(2)),env)).ok,false);await assert.rejects(changeAccount(A,'enable',{currentPassword:'wrong'}),/password/);const a=await changeAccount(A,'enable',{currentPassword:password});assert.equal(a.disabled,false);assert.equal(a.sessionVersion,3);assert.equal((await requireSession(request(await token(2)),env)).ok,false);});
test('deletion drains requests then removes every scoped store, identity index and subscription while preserving another user',async()=>{const a=await seed();for(const n of STORE_INVENTORY){if(['samvit-account-deletions','samvit-runtime-secrets'].includes(n))continue;await store(n).setJSON('accounts/'+A+'/record',{private:true});await store(n).setJSON('accounts/'+B+'/record',{other:true});}await store('samvit-subscription').setJSON('sub:'+A,{planId:'free',status:'active'});await store('samvit-connections').setJSON('workspace:'+A,{connections:[]});await store('samvit-budget').setJSON('budget:'+A+':2026-09',{microUsd:1});await requestAccountDeletion(A,{currentPassword:password},env,{now:1000});const job=await store('samvit-account-deletions').get(A,{type:'json'});assert.equal(await purgeAccount(job,2000),false);assert.equal(await purgeAccount(job,301001),true);for(const n of STORE_INVENTORY){if(['samvit-account-deletions','samvit-runtime-secrets'].includes(n))continue;assert.equal(await store(n).get('accounts/'+A+'/record'),null,n);assert.ok(await store(n).get('accounts/'+B+'/record'),n);}assert.equal(await store('samvit-accounts').get('account:'+A),null);assert.equal(await store('samvit-accounts').get(await emailKey(a.email)),null);assert.equal(await store('samvit-subscription').get('sub:'+A),null);});
test('active paid subscription refuses deletion without disabling account',async()=>{await seed();await store('samvit-subscription').setJSON('sub:'+A,{planId:'pro',status:'active'});await assert.rejects(requestAccountDeletion(A,{currentPassword:password},env),/Cancel your paid subscription/);assert.equal((await store('samvit-accounts').get('account:'+A,{type:'json'})).disabled,false);});
test('every literal application store referenced by server code is in deletion inventory',async()=>{async function walk(dir){for(const e of await readdir(dir,{withFileTypes:true})){const p=dir+'/'+e.name;if(e.isDirectory())await walk(p);else if(/\.m?js$/.test(p)){const source=await readFile(p,'utf8');for(const match of source.matchAll(/(?:getStore|accountStore)\(\s*['"](samvit-[a-z-]+)['"]/g))assert.ok(STORE_INVENTORY.includes(match[1]),p+': '+match[1]);for(const match of source.matchAll(/(?:STORE|STORE_NAME)\s*=\s*['"](samvit-[a-z-]+)['"]/g))assert.ok(STORE_INVENTORY.includes(match[1]),p+': '+match[1]);}}}await walk('netlify');});
test('V14: ungated fresh instance registers openly — no owner claim anywhere; public report leaks no config facts',async t=>{stores.clear();const {registerAccount,accountRole}=await import('../netlify/lib/accounts.js'),{default:setup}=await import('../netlify/functions/setup.mjs');
 // Without RESEND, the account store alone can't activate, but registration
 // itself is open: the very first stranger becomes an ordinary UNVERIFIED
 // member — never an owner, and no claim secret exists to even try.
 const first=await registerAccount({email:'first@example.test',password},env);
 assert.match(first.id,/^usr_/);assert.equal(accountRole({id:first.id,emailVerified:false},env),'unverified');
 assert.equal(await store('samvit-accounts').get('meta'),null);
 const report=await(await setup(new Request('https://samvit.test/api/setup'))).json();
 assert.equal(report.ready,false);
 assert.ok(!report.checks.some(c=>c.key==='OWNER_CLAIM'),'no ownership checks remain');
 assert.equal('registrationGate'in report,false);
 assert.ok(!JSON.stringify(report).includes('PROVIDER_ACCESS'));
 assert.ok(!JSON.stringify(report).includes('ownerAccountId'));});
test('deletion worker refuses a paid subscription that appeared during the drain period',async()=>{await seed();await requestAccountDeletion(A,{currentPassword:password},env,{now:1000});await store('samvit-subscription').setJSON('sub:'+A,{planId:'pro',status:'active'});const job=await store('samvit-account-deletions').get(A,{type:'json'});await assert.rejects(purgeAccount(job,301001,env),/Cancel your paid subscription/);assert.ok(await store('samvit-accounts').get('account:'+A));});
