import test,{mock} from 'node:test';import assert from 'node:assert/strict';import {createFakeStore} from './helpers/fake-store.js';
const stores=new Map(),store=n=>{if(!stores.has(n))stores.set(n,createFakeStore());return stores.get(n);};mock.module('@netlify/blobs',{namedExports:{getStore:store}});
const {createJob,getJob,commandJob,jobKey,JOB_STORE}=await import('../netlify/lib/intelligence/jobs.js'),{runJob}=await import('../netlify/lib/intelligence/runtime.js'),{callModel}=await import('../netlify/lib/intelligence/model-call.js'),{authorizeWorker,dispatchJob}=await import('../netlify/lib/intelligence/dispatch.js'),{chargeToolBudget}=await import('../netlify/lib/intelligence/tool-budget.js'),{embedTexts}=await import('../netlify/lib/intelligence/embeddings.js'),{signToken}=await import('../netlify/lib/security.js'),{default:endpoint}=await import('../netlify/functions/orchestration.mjs');
const A='usr_00000000-0000-0000-0000-000000000001',B='usr_00000000-0000-0000-0000-000000000002',secret='s'.repeat(48),config={SESSION_SECRET:secret,NODE_ENV:'production',SAMVIT_PUBLIC_ORIGIN:'https://samvit.test',OPENAI_API_KEY:'fixture-key'},env={get:k=>config[k]};
async function seed(){stores.clear();for(const id of [A,B]){await store('samvit-accounts').setJSON('account:'+id,{id,emailVerified:true,sessionVersion:1});await store('samvit-subscription').setJSON('sub:'+id,{planId:'pro',status:'active'});}await store('samvit-accounts').setJSON('meta',{ownerAccountId:A,migrationComplete:true});}
const node=(id,dependencies=[],kind='work')=>({id,description:id,dependencies,kind,tools:[],capability:'general',status:'pending',attempts:0});
async function graph(tasks,extra={}){const j=await createJob(A,{requestId:crypto.randomUUID(),goal:'Solve a complex task'},env);await store(JOB_STORE).setJSON(jobKey(A,j.id),{...j,spec:{strategy:'critique',complexity:'high',freshness_required:false},tasks,...extra});return j;}
const result=(output='Result')=>({output,evidence:[],models:['fixture'],steps:1});
test('independent DAG nodes execute in parallel, with one synthesis after both settle',async()=>{await seed();const j=await graph([node('a'),node('b'),node('s',['a','b'],'synthesis')]);let running=0,peak=0,finished=0;await runJob(A,j.id,env,{agent:async(_ctx,t,input)=>{if(t.kind==='synthesis'){assert.equal(finished,2);assert.equal(input.dependencies.length,2);return result('combined');}running++;peak=Math.max(peak,running);await new Promise(r=>setTimeout(r,25));finished++;running--;return result(t.id);}});assert.equal(peak,2);assert.equal((await getJob(A,j.id)).output,'combined');});
test('partial failure reaches synthesis with explicit failed dependencies, repair is bounded',async()=>{await seed();const j=await graph([node('a'),node('b'),node('s',['a','b'],'synthesis')]);let failures=0;await runJob(A,j.id,env,{modelCall:async()=>({content:'Try a narrower task'}),agent:async(_ctx,t,input)=>{if(t.id==='a'){failures++;throw Error('provider failed');}if(t.id==='s')assert.ok(input.dependencies.some(t=>t.status==='failed'));return result();}});const saved=await getJob(A,j.id);assert.equal(saved.status,'partial');assert.equal(saved.replans,1);assert.equal(failures,2);});
test('parallel budget reservations are atomic and cannot exceed the mission cap',async()=>{await seed();const j=await graph([node('a'),node('b'),node('s',['a','b'],'synthesis')],{replans:1});const before=await getJob(A,j.id);await store(JOB_STORE).setJSON(jobKey(A,j.id),{...before,limits:{...before.limits,maxMicroUsd:100}});let dispatched=0;await runJob(A,j.id,env,{agent:async ctx=>{await ctx.reserveCall(70);dispatched++;return result();}});const saved=await getJob(A,j.id);assert.equal(dispatched,1);assert.equal(saved.spentMicroUsd,70);});
test('pause during execution prevents an old worker from committing output; resume keeps budget spent',async()=>{await seed();const j=await graph([node('a')]);let release,entered;const started=new Promise(r=>entered=r),held=new Promise(r=>release=r);const running=runJob(A,j.id,env,{agent:async ctx=>{await ctx.reserveCall(10);entered();await held;return result('should not commit');}});await started;await commandJob(A,j.id,'pause');release();await running;let saved=await getJob(A,j.id);assert.equal(saved.status,'paused');assert.equal(saved.output,undefined);await commandJob(A,j.id,'resume');await runJob(A,j.id,env,{agent:async()=>result('resumed')});saved=await getJob(A,j.id);assert.equal(saved.output,'resumed');assert.equal(saved.spentMicroUsd,10);});
test('expired worker leases fence stale output and a recovery resumes durable state',async()=>{await seed();const j=await graph([node('a')]);let clock=1000,release,entered;const started=new Promise(r=>entered=r),held=new Promise(r=>release=r);const old=runJob(A,j.id,env,{now:()=>clock,agent:async()=>{entered();await held;return result('stale');}});await started;clock=92001;await runJob(A,j.id,env,{now:()=>clock,agent:async()=>result('fresh')});release();await old;assert.equal((await getJob(A,j.id)).output,'fresh');});
test('worker tokens are short-lived, audience-bound, and cannot be replaced by a session token',async()=>{await seed();const j=await createJob(A,{requestId:crypto.randomUUID(),goal:'2+2'},env);let request;await dispatchJob(j,env,{fetcher:async(url,init)=>{request=new Request(url,init);return new Response(null,{status:202});}});assert.equal((await authorizeWorker(request,env)).accountId,A);const session=await signToken(secret,{sub:A,version:1,exp:Date.now()+60000});await assert.rejects(authorizeWorker(new Request('https://samvit.test/worker',{method:'POST',headers:{authorization:'Bearer '+session}}),env),/Invalid worker/);});
test('orchestration endpoint rejects cross-account job reads, cross-origin writes and forged worker state',async t=>{await seed();for(const [k,v]of Object.entries(config)){const old=process.env[k];process.env[k]=v;t.after(()=>old===undefined?delete process.env[k]:process.env[k]=old);}const j=await createJob(A,{requestId:crypto.randomUUID(),goal:'2+2'},env);const token=await signToken(secret,{sub:B,version:1,exp:Date.now()+60000});const req=new Request('https://samvit.test/api/orchestration?id='+j.id,{headers:{cookie:'samvit_session='+token}});assert.equal((await endpoint(req,{})).status,404);assert.equal((await endpoint(new Request('https://samvit.test/api/orchestration',{method:'POST',headers:{cookie:'samvit_session='+token,origin:'https://evil.test'},body:'{}'}),{})).status,403);});
test('native model calls use monthly and mission budgets and preserve configured-unverified access semantics',async t=>{await seed();let requests=0,reserved=0;const original=global.fetch;global.fetch=async()=>{requests++;return Response.json({choices:[{finish_reason:'stop',message:{content:'Actual fixture response'}}],usage:{prompt_tokens:10,completion_tokens:8}});};t.after(()=>global.fetch=original);const ctx={accountId:A,env,signal:new AbortController().signal,assertActive:async()=>{},reserveCall:async n=>reserved+=n,trace:async()=>{}};const answer=await callModel(ctx,{system:'Policy',history:[{role:'user',content:'Define gravity'}]});assert.equal(answer.content,'Actual fixture response');assert.equal(requests,1);assert.ok(reserved>0);const budget=await store('samvit-budget').get('budget:'+A+':'+new Date().toISOString().slice(0,7),{type:'json'});assert.ok(budget.microUsd>0);assert.equal(Object.keys(budget.reservations).length,0);await assert.rejects(callModel(ctx,{system:'x',history:[{role:'user',content:'x'.repeat(71000)}]}),/context limit/);});
test('paid tools are bounded by monthly budget in addition to job budgets',async()=>{await seed();await chargeToolBudget(A,1000,env);const record=await store('samvit-budget').get('budget:'+A+':'+new Date().toISOString().slice(0,7),{type:'json'});assert.equal(record.microUsd,1000);await assert.rejects(chargeToolBudget(A,20000000,{get:k=>k==='SAMVIT_MONTHLY_BUDGET_USD'?'0.001':env.get(k)}),/allowance/);});
test('semantic adapter validates real vectors and meters the embedding request',async()=>{await seed();let called=false;const e={get:k=>({SAMVIT_SEMANTIC_MEMORY:'true',SAMVIT_EMBEDDING_USD_PER_MILLION:'0.02'})[k]||env.get(k)},ctx={accountId:A,env:e,signal:new AbortController().signal,assertActive:async()=>{},reserveCall:async()=>{},trace:async()=>{}};const vectors=await embedTexts(['astronomy'],ctx,{fetcher:async(url,opts)=>{called=true;assert.equal(url,'https://api.openai.com/v1/embeddings');assert.equal(JSON.parse(opts.body).dimensions,256);return Response.json({data:[{index:0,embedding:Array(256).fill(.1)}],usage:{total_tokens:4}});}});assert.ok(called);assert.equal(vectors[0].length,256);});
test('ten simultaneous accounts finish cheap jobs without shared output or budget state',async()=>{stores.clear();await Promise.all(Array.from({length:10},async(_,i)=>{const id='usr_00000000-0000-0000-0000-'+String(i+1).padStart(12,'0');await store('samvit-accounts').setJSON('account:'+id,{id,emailVerified:true,sessionVersion:1});await store('samvit-subscription').setJSON('sub:'+id,{planId:'free',status:'active'});const j=await createJob(id,{requestId:crypto.randomUUID(),goal:`${i}+2`},env);await runJob(id,j.id,env,{modelCall:async()=>assert.fail()});assert.equal((await getJob(id,j.id)).output,String(i+2));}));});
