import {priceStatusLabel} from '../shared/pricing-policy.js';
import {initWorkbench,setWorkbenchAccount,renderTeams,renderConnections,refreshConnections,routingOptions,chooseTeamPlan,teamRunning} from './workbench.js';
import {initAppearance,renderAppearance} from './appearance.js';
import {renderAssistant,stopAssistant,setAssistantAccount} from './intelligence.js';
import {renderComputers,stopComputers} from './computers.js';
import {TEAM_SIZES} from '../shared/teams.js';
import {MODEL_CATALOG,modelPrice,CATALOG_REVIEWED} from '../shared/catalog.js';
import {PLAN_CAPABILITIES} from '../shared/models.js';
import {iterateSSE} from '../shared/sse.js';
import {installVoice} from './voice.js';
const $=selector=>document.querySelector(selector);
const main=$('#main');
const names={operations:'Billing operations',chat:'Chat',models:'Model library',council:'AI Council',missions:'Goal planner',projects:'Projects',memory:'Memory',analytics:'Usage & insights',plans:'Billing & plans',email:'Confirm account',recover:'Account recovery',account:'Account security',settings:'Settings',setup:'Setup check',agents:'Agent studio',connections:'Connections',appearance:'Your workspace',computers:'Computers'};
const symbols={claude:'✳',openai:'◎',gemini:'✦',grok:'𝕏'};
const state={status:null,page:'agents',tier:'balanced',model:'auto',messages:[],conversation:null,abort:null,saving:false,history:[],draft:'',fallback:false,renderId:0};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let liveCatalog=[],accountEpoch=0;
const rateAge=m=>priceStatusLabel(m.pricing||{kind:'static-fallback',checkedAt:Date.parse(CATALOG_REVIEWED)});
const money=value=>typeof value==='number'?`$${value.toFixed(value<.01?5:3)}`:'Not reported';
const connected=id=>Boolean(state.status?.authenticated&&state.status?.providers?.[id]);
const notify=message=>{const toast=$('#toast');toast.textContent=message;toast.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.hidden=true,6000);};
function banner(message){$('#notice').textContent=message;$('#notice').hidden=!message;}
async function api(path,body,method=body?'POST':'GET',signal){
 const epoch=accountEpoch;
 const response=await fetch(path,{method,credentials:'same-origin',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal});
 if(epoch!==accountEpoch)throw new DOMException('Account changed','AbortError');
 const type=response.headers.get('content-type')||'';
 if(!type.includes('application/json')&&!type.includes('text/event-stream')) throw new Error('The backend is unavailable. Start Samvit with Netlify to connect your workspace.');
 if(!response.ok){let error;try{error=await response.json();}catch{}if(response.status===401&&state.status?.authenticated)showLogin();throw new Error(error?.message||error?.error||`Request failed (${response.status}).`);}
 return type.includes('text/event-stream')?response:response.json();
}
function showLogin(){if(!$('#login-dialog').open)$('#login-dialog').showModal();}
$('#persistent-signin').onclick=showLogin;
async function boot(){
 try{
  const nextStatus=await api('/api/status');
  if(state.status?.account?.id!==nextStatus.account?.id){accountEpoch++;state.abort?.abort();state.messages=[];state.conversation=null;state.history=[];state.draft='';$('#history').replaceChildren();}
  state.status=nextStatus;
  setWorkbenchAccount(state.status.account?.id || null);
  try{liveCatalog=(await api('/api/model-catalog')).models||[];}catch{}
  $('#connection').textContent=`${state.status.configuredCount} connected`;
  $('#connection').classList.toggle('online',state.status.configuredCount>0&&state.status.authenticated);
  $('#plan-label').textContent=state.status.subscription?.planId?`${state.status.subscription.planId} workspace`:'Shared workspace';
  if(!state.status.authenticated){showLogin();banner('Sign in to your workspace to continue.');}
  else if(state.status.account?.emailVerified===false)banner('Verify your email to run models or manage billing. Use Account recovery to request a link.');
  else if(!state.status.configuredCount)banner('Your workspace is ready. Add a provider in Connections to start chatting.');
  else banner(state.status.protectedApp?'':'Development mode · This is a shared workspace.');
  if(state.status.authenticated)await refreshConnections();render();if(state.status.authenticated)await refreshHistory();
 }catch(err){state.status=null;$('#connection').textContent='Not connected';$('#connection').classList.remove('online');$('#plan-label').textContent='Interface preview';banner('Interface preview · The AI backend is not connected. You can explore the workspace and model library.');render();}
}
function navigate(page){location.hash=page;if(state.page===page)render();}
function pageHeader(title,description,eyebrow='YOUR WORKSPACE'){return `<div class="page-head"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p class="intro">${esc(description)}</p></div></div>`;}
function empty(message){return `<div class="empty"><b>✳</b>${esc(message)}</div>`;}
function requireConnection(){if(!state.status?.authenticated){notify('Connect the backend and sign in to use this feature.');return false;}return true;}
function render(){
 stopAssistant();stopComputers();setAssistantAccount(state.status?.account?.id||null);names.assistant='Samvit';
 state.page=Object.hasOwn(names,location.hash.slice(1).split('?')[0])?location.hash.slice(1).split('?')[0]:'assistant';const id=++state.renderId;
 $('#page-label').textContent=names[state.page];document.title=`${names[state.page]} · Samvit`;
 document.querySelectorAll('[data-page]').forEach(link=>{link.classList.toggle('active',link.dataset.page===state.page);if(link.dataset.page===state.page)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');});
 $('#sidebar').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');
 if(state.page==='assistant'){renderAssistant({main,api,esc,notify});return;}
 if(state.page==='computers'){renderComputers({main,api,esc,notify});return;}
 if(state.page==='operations')renderOperations();else if(state.page==='email')renderEmailConfirmation();else if(state.page==='recover')renderRecovery();else if(state.page==='account')renderAccount();else if(state.page==='setup')renderSetup();else if(state.page==='agents')renderTeams();else if(state.page==='connections')renderConnections();else if(state.page==='appearance')renderAppearance();else if(state.page==='chat')renderChat();else if(state.page==='models')renderModels();else if(state.page==='council')renderCouncil();else if(['memory','projects','missions'].includes(state.page))renderRecords(state.page,id);else if(state.page==='plans')renderPlans();else if(state.page==='settings')renderSettings();else renderAnalytics(id);
}
const options=()=>`<option value="auto">✳ Auto · ${state.tier}</option>`+MODEL_CATALOG.map(m=>`<option value="${m.id}" ${state.model===m.id?'selected':''} ${!connected(m.provider)?'disabled':''}>${esc(m.label)}${connected(m.provider)?'':' · not connected'}</option>`).join('')+routingOptions().map(t=>`<option value="${esc(t.id)}" ${state.model===t.id?'selected':''}>${esc(t.label)}</option>`).join('');
function renderChat(){
 const hasMessages=state.messages.length>0;
 main.innerHTML=`<div class="chat-page ${hasMessages?'has-messages':''}">
 ${hasMessages?'<div class="conversation-title"><h2>Your conversation</h2><button class="secondary" id="export-chat">Export text ↗</button></div>':`<section class="hero"><div class="eyebrow">A LITTLE CURIOSITY GOES A LONG WAY</div><h1>Big ideas start with<br><em>a simple question.</em></h1><p>Your favorite AI models, together in one thoughtful workspace.<br>Find your perspective. Follow the possibility.</p></section>`}
 <div id="messages" class="messages" aria-label="Conversation"></div>
 <div class="mode-bar"><span>Find your flow</span>${[['economy','↯ Everyday'],['balanced','✳ Balanced'],['frontier','◈ Deep work']].map(([id,label])=>`<button class="chip ${state.tier===id?'active':''}" data-tier="${id}" aria-pressed="${state.tier===id}">${label}</button>`).join('')}</div>
 <form class="composer" id="chat-form"><label class="sr-label" for="prompt" hidden>Your message</label><textarea id="prompt" aria-label="Your message" placeholder="Ask anything. Make something. Go somewhere new…" maxlength="24000" required>${esc(state.draft)}</textarea><div class="composer-bottom"><select id="model-picker" class="model-select" aria-label="Choose a model">${options()}</select><label title="If a model fails before responding, try a model in the same price category with no higher estimated cost."><input type="checkbox" id="fallback" ${state.fallback?'checked':''}> Allow fallback</label><button class="send" id="send" aria-label="${state.abort?'Stop generating':'Send message'}" type="${state.abort?'button':'submit'}">${state.abort?'■':'↑'}</button></div></form>
 <div class="composer-note"><span id="routing-note">Auto chooses an available model by your price preference.</span><span>Enter to send · Shift + Enter for a new line</span></div>
 ${hasMessages?'':`<div class="ideas-header"><span>START WITH A SPARK</span><span>A blank page, full of possibility</span></div><div class="ideas"><button class="idea" data-prompt="Help me turn a rough idea into a clear, useful first draft. Ask me what I want to create."><span class="symbol">✎</span><span class="arrow">↗</span><strong>Make something yours</strong><p>Find the right words for your next big idea.</p></button><button class="idea" data-prompt="Help me understand a difficult topic. Ask what I am studying, then explain it with a simple example."><span class="symbol">✧</span><span class="arrow">↗</span><strong>Connect the dots</strong><p>Make the complicated feel a little simpler.</p></button><button class="idea" data-prompt="Help me plan a project. Ask about my goal, available time, and the first obstacle."><span class="symbol">↗</span><span class="arrow">↗</span><strong>Find your next move</strong><p>Turn a what-if into a what-comes-next.</p></button></div><div class="model-strip"><span><b>✳</b> Claude</span><span><b>◎</b> OpenAI</span><span><b>✦</b> Gemini</span><span><b>𝕏</b> Grok</span><small>Different minds. More possibility.</small></div>`}</div>`;
 renderMessages();
 $('#prompt').addEventListener('input',event=>state.draft=event.target.value);
 $('#fallback').onchange=event=>state.fallback=event.target.checked;
 $('#model-picker').onchange=event=>{state.model=event.target.value;};
 document.querySelectorAll('[data-tier]').forEach(button=>button.onclick=()=>{state.tier=button.dataset.tier;state.model='auto';renderChat();});
 document.querySelectorAll('[data-prompt]').forEach(button=>button.onclick=()=>{state.draft=button.dataset.prompt;$('#prompt').value=state.draft;$('#prompt').focus();});
 $('#chat-form').onsubmit=event=>{event.preventDefault();sendMessage();};
 $('#prompt').onkeydown=event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();if(!state.abort)sendMessage();}};
 if(state.abort)$('#send').onclick=()=>state.abort.abort();
 if($('#export-chat'))$('#export-chat').onclick=exportChat;
}
function renderContent(element,text){
 element.replaceChildren();const chunks=String(text).split(/(```[\s\S]*?```)/g);
 for(const chunk of chunks){if(chunk.startsWith('```')){const pre=document.createElement('pre'),code=document.createElement('code');code.textContent=chunk.slice(3,-3).replace(/^[\w+-]*\n/,'');pre.append(code);element.append(pre);}else{const span=document.createElement('span');span.textContent=chunk;element.append(span);}}
}
function renderMessages(){
 const container=$('#messages');if(!container)return;container.replaceChildren();
 state.messages.forEach(message=>{const article=document.createElement('article');article.className=`message ${message.role}`;
 const heading=document.createElement('div');heading.className='message-heading';heading.textContent=message.role==='user'?'You':`✳ ${MODEL_CATALOG.find(m=>m.id===message.model)?.label||message.model||'Samvit'}`;
 const content=document.createElement('div');content.className='message-content';renderContent(content,message.content||'Thinking…');article.append(heading,content);
 if(message.error){const error=document.createElement('p');error.className='error';error.textContent=message.error;article.append(error);}
 if(message.role==='assistant'&&message.content){const meta=document.createElement('div');meta.className='message-meta';meta.textContent=message.costUsd!=null?`Estimated API cost ${money(message.costUsd)}`:message.complete?'Complete':'Partial response';const copy=document.createElement('button');copy.textContent='Copy';copy.onclick=()=>navigator.clipboard.writeText(message.content).then(()=>notify('Copied to clipboard.')).catch(()=>notify('Clipboard access is unavailable. Use Export text.'));meta.append(copy);article.append(meta);}
 container.append(article);});
}
async function sendMessage(){
 const epoch=accountEpoch;
 const prompt=state.draft.trim();if(!prompt||state.abort)return;if(state.saving){notify('Finishing the previous save. Please try again in a moment.');return;}if(!requireConnection())return;
 if(!Object.values(state.status.providers).some(Boolean)&&!routingOptions().length){notify('Connect at least one provider first.');return;}
 const selected=MODEL_CATALOG.find(m=>m.id===state.model);
 // Only completed turns enter future provider context; incomplete answers stay visible.
 const messages=state.messages.filter((m,i)=>m.role==='assistant'?m.complete:state.messages[i+1]?.complete).map(({role,content})=>({role,content}));messages.push({role:'user',content:prompt});
 state.messages.push({role:'user',content:prompt});const answer={role:'assistant',content:'',model:selected?.id};state.messages.push(answer);state.draft='';state.abort=new AbortController();renderChat();
 try{
  const response=await api(/^(connection|combo):/.test(state.model)?'/api/routed-chat':'/api/chat',{target:state.model,provider:selected?.provider||'auto',model:selected?.id,tier:state.tier,messages,allowFallback:state.fallback,maxTokens:2048},'POST',state.abort.signal);
  let terminal=false;
  for await(const {data} of iterateSSE(response)){
   if(epoch!==accountEpoch)return;
   const event=JSON.parse(data);
   if(event.selected){answer.model=event.model;if(event.fallback)notify(`Switched to ${MODEL_CATALOG.find(m=>m.id===event.model)?.label||event.model}.`);}
   if(event.delta)answer.content+=event.delta;
   if(event.error)throw new Error(event.error);
   if(event.done){terminal=true;answer.complete=true;answer.costUsd=event.costUsd;answer.model=event.model;answer.provider=event.provider;}
   renderMessages();
  }
  if(!terminal)throw new Error('The stream ended early. Your partial response is preserved.');
 }catch(err){answer.error=err.name==='AbortError'?'Stopped. Partial response preserved.':err.message;}
 finally{if(epoch!==accountEpoch)return;state.abort=null;state.saving=true;if(state.page==='chat')renderChat();await saveConversation();state.saving=false;if(state.page==='chat')renderChat();}
}
async function saveConversation(){
 try{const result=await api('/api/conversations',{...(state.conversation?{id:state.conversation}:{}),title:state.messages.find(m=>m.role==='user')?.content.slice(0,80)||'Conversation',messages:state.messages,provider:state.messages.at(-1)?.provider||'auto',model:state.messages.at(-1)?.model},state.conversation?'PUT':'POST');state.conversation=result.conversation.id;await refreshHistory();}catch{notify('Conversation is still on this page, but could not be saved. Use Export text before leaving.');}
}
async function refreshHistory(){
 if(!state.status?.authenticated)return;
 try{const result=await api('/api/conversations');state.history=result.conversations;$('#history').replaceChildren();
  if(!state.history.length)$('#history').innerHTML='<p>Your next idea starts here.</p>';
  state.history.slice(0,12).forEach(item=>{const button=document.createElement('button');button.textContent=item.title;button.title=item.title;button.onclick=async()=>{if(state.abort||state.saving){notify('Wait for the current response to finish saving.');return;}try{const {conversation}=await api(`/api/conversations?id=${encodeURIComponent(item.id)}`);state.messages=conversation.messages;state.conversation=conversation.id;navigate('chat');}catch(err){notify(err.message);}};$('#history').append(button);});
 }catch{$('#history').innerHTML='<p>Conversation history is unavailable.</p>';}
}
function exportChat(){const text=state.messages.map(m=>`${m.role==='user'?'You':m.model||'Samvit'}\n\n${m.content}${m.error?`\n\n[${m.error}]`:''}`).join('\n\n---\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const link=document.createElement('a');link.href=url;link.download='samvit-conversation.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function renderModels(){
 main.innerHTML=`<section class="page">${pageHeader('Different minds. Your choice.','Find a model for the way you work. Compare standard text API rates, then choose your starting point.','THE MODEL LIBRARY')}<div class="filters"><input class="search" id="model-search" type="search" placeholder="Find a model or provider…" aria-label="Search models"><select id="tier-filter" aria-label="Filter price category"><option value="all">Every price range</option value="economy">Everyday · lower cost</option><option value="balanced">Balanced</option><option value="frontier">Deep work · premium</option></select></div><div id="model-grid" class="grid"></div><p class="intro spaced">Each card labels its price source and last check. Direct-provider rates use the dated static fallback; the Connections catalog refreshes OpenRouter prices. API usage is separate from workspace plan pricing. A connected key does not guarantee access to every model.</p></section>`;
 function draw(){const query=$('#model-search').value.toLowerCase(),tier=$('#tier-filter').value;
 const models=[...MODEL_CATALOG,...liveCatalog.filter(m=>m.provider==='openrouter')].filter(m=>(m.label+' '+m.id+' '+m.provider).toLowerCase().includes(query)&&(tier==='all'||tier===m.tier));
 $('#model-grid').innerHTML=models.length?models.map(m=>{const display=liveCatalog.find(x=>x.provider===m.provider&&x.id===m.id)||m;const price=modelPrice(display);return `<article class="card"><div class="card-head"><span class="provider-logo">${symbols[m.provider]||'↗'}</span><span class="tag">${m.tier||'LIVE GATEWAY'}</span></div><h3>${esc(m.label)}</h3><p>${esc(m.description||m.id)}</p><div class="prices"><div>$${price.input}<small>INPUT / 1M TOKENS</small></div><div>$${price.output}<small>OUTPUT / 1M TOKENS</small></div></div><p class="rate-age">${esc(rateAge(display))}</p><a class="source" href="${esc(m.source||m.pricing?.source)}" target="_blank" rel="noopener noreferrer">Provider rates ↗</a><div class="card-bottom"><small>${connected(m.provider)?'Provider connected':'Not connected'}</small>${m.provider==='openrouter'?'<a href="#connections">Add in Connections ↗</a>':`<button data-select="${m.id}" ${connected(m.provider)?'':'disabled'}>Start a chat ↗</button>`}</div></article>`;}).join(''):empty('No models match that search.');
 document.querySelectorAll('[data-select]').forEach(button=>button.onclick=()=>{state.model=button.dataset.select;state.tier=MODEL_CATALOG.find(m=>m.id===state.model).tier;navigate('chat');});}
 $('#model-search').oninput=draw;$('#tier-filter').onchange=draw;draw();
}
function renderCouncil(){
 const allowed=state.status?.subscription?.entitlements?.council;
 main.innerHTML=`<section class="page">${pageHeader('A second perspective. Or a third.','Ask the same question across models. Read their answers side by side and decide what makes sense to you.','AI COUNCIL')}<div class="panel"><form id="council-form"><label>Your question<textarea id="council-prompt" maxlength="4000" rows="4" required placeholder="What would you like a few different perspectives on?"></textarea></label><div class="form-row">${['claude','openai','gemini','grok'].map(id=>`<label><input type="checkbox" name="provider" value="${id}" ${connected(id)?'':'disabled'}>${symbols[id]} ${id==='openai'?'OpenAI':id[0].toUpperCase()+id.slice(1)}</label>`).join('')}</div><div class="form-row"><label><input id="critique" type="checkbox" ${allowed?'':'disabled'}> Add a critique round (extra usage)</label><button class="primary" ${allowed?'':'disabled'}>Ask the council ↗</button></div>${allowed?'':'<p>Council requires an active Ultra or Ultimate workspace plan.</p>'}</form></div><div class="council-grid" id="council-results"></div></section>`;
 $('#council-form').onsubmit=async event=>{event.preventDefault();if(!requireConnection())return;const providers=[...document.querySelectorAll('input[name="provider"]:checked')].map(el=>el.value);if(providers.length<2){notify('Choose at least two connected providers.');return;}const button=event.submitter;button.disabled=true;const container=$('#council-results');container.replaceChildren();const slots={};
 providers.forEach(id=>{const card=document.createElement('article');card.className='card';const title=document.createElement('h3');title.textContent=id;const text=document.createElement('div');text.textContent='Thinking…';card.append(title,text);container.append(card);slots[id]={text,content:'',card};});
 try{const response=await api('/api/council',{providers,prompt:$('#council-prompt').value,critique:$('#critique').checked});let terminal=false;
 for await(const {data}of iterateSSE(response)){const chunk=JSON.parse(data),slot=slots[chunk.provider];if(chunk.allDone)terminal=true;if(!slot)continue;if(chunk.delta){slot.content+=chunk.delta;slot.text.textContent=slot.content;}if(chunk.error){const error=document.createElement('p');error.className='error';error.textContent=chunk.error;slot.card.append(error);}if(chunk.critique){const critique=document.createElement('p');critique.textContent=`Critique: ${chunk.critique}`;slot.card.append(critique);}}
 if(!terminal)throw new Error('Comparison ended early.');}catch(err){notify(err.message);}finally{button.disabled=false;}};
}
async function renderRecords(kind,renderId){
 const config={memory:['Remember what matters.','Save useful context here. Memories stay in the shared workspace; they are not automatically sent with chat messages.'],projects:['Make space for the bigger picture.','Keep your projects and their current status together.'],missions:['A little direction goes a long way.','Turn a goal into a plan, then track each step. Plans do not execute tasks automatically.']}[kind];
 main.innerHTML=`<section class="page">${pageHeader(...config)}<div class="panel"><form id="record-form">${kind==='memory'?'<label>Memory<textarea name="text" maxlength="5000" rows="3" required placeholder="A preference, a useful detail, something worth keeping…"></textarea></label>':kind==='projects'?'<label>Project name<input name="name" maxlength="120" required placeholder="Your next project"></label><label>Description<textarea name="description" rows="2" maxlength="2000" placeholder="What are you working toward?"></textarea></label>':'<label>Your goal<textarea name="goal" rows="3" maxlength="2000" required placeholder="What would you like to accomplish?"></textarea></label>'}<div class="form-row"><button class="primary">${kind==='missions'?'Generate a plan ↗':kind==='memory'?'Save memory +':'Create project +'}</button></div></form></div><div class="list" id="records">${empty('Loading your workspace…')}</div></section>`;
 $('#record-form').onsubmit=async event=>{event.preventDefault();if(!requireConnection())return;const button=event.submitter;button.disabled=true;try{let body=Object.fromEntries(new FormData(event.target));if(kind==='missions'){const model=MODEL_CATALOG.find(m=>connected(m.provider)&&m.tier==='economy');if(!model)throw new Error('Connect a provider first.');const response=await api('/api/workflow',{goal:body.goal,provider:model.provider,model:model.id});body=response.mission;}await api(`/api/${kind}`,body);notify('Saved to your workspace.');render();}catch(err){notify(err.message);button.disabled=false;}};
 if(!state.status?.authenticated){$('#records').innerHTML=empty('Connect your workspace to see saved items.');return;}
 try{const result=await api(`/api/${kind}`);if(renderId!==state.renderId)return;let items=result[kind==='memory'?'memories':kind];if(kind==='missions')items=await Promise.all(items.map(async item=>(await api(`/api/missions?id=${encodeURIComponent(item.id)}`)).mission));if(renderId!==state.renderId)return;
 const container=$('#records');container.replaceChildren();if(!items.length)container.innerHTML=empty('Nothing here yet. Start with something small.');
 items.forEach(item=>{const card=document.createElement('article');card.className='record';const h=document.createElement('h3');h.textContent=item.name||item.title||'Memory';const p=document.createElement('p');p.textContent=item.text||item.description||item.summary||'';card.append(h,p);
 if(kind==='projects'){const status=document.createElement('select');status.setAttribute('aria-label',`Status of ${item.name}`);for(const value of ['active','on-hold','completed','archived'])status.add(new Option(value,value,value===item.status,value===item.status));status.onchange=async()=>{try{await api('/api/projects',{id:item.id,status:status.value},'PUT');notify('Project updated.');}catch(err){notify(err.message);status.value=item.status;}};card.append(status);}
 if(kind==='missions')for(const [index,step] of (item.steps||[]).entries()){const row=document.createElement('label');row.className='step';const check=document.createElement('input');check.type='checkbox';check.checked=step.completed;const detail=document.createElement('span');detail.textContent=step.title;const desc=document.createElement('p');desc.textContent=step.detail;detail.append(desc);row.append(check,detail);card.append(row);check.onchange=async()=>{check.disabled=true;try{const latest=(await api(`/api/missions?id=${encodeURIComponent(item.id)}`)).mission;latest.steps[index].completed=check.checked;await api('/api/missions',{id:item.id,steps:latest.steps},'PUT');}catch(err){notify(err.message);check.checked=!check.checked;}finally{check.disabled=false;}};}
 const actions=document.createElement('div');actions.className='record-actions';const remove=document.createElement('button');remove.textContent='Delete';remove.onclick=async()=>{if(!confirm('Delete this saved item?'))return;try{await api(`/api/${kind}?id=${encodeURIComponent(item.id)}`,null,'DELETE');render();}catch(err){notify(err.message);}};actions.append(remove);card.append(actions);container.append(card);});
 }catch(err){if(renderId===state.renderId)$('#records').innerHTML=empty(err.message);}
}
function renderPlans(){
 const student=state.status?.billing?.studentDiscount;
 main.innerHTML=`<section class="page">${pageHeader('Room to grow.','Billing plans define your account’s monthly allowance. Goal planning lives separately in the Goal planner workspace.','BILLING & PLANS')}<div class="plan-grid">${Object.entries(PLAN_CAPABILITIES).map(([id,plan])=>`<article class="card ${id==='ultra'?'featured':''}"><span class="tag">${id==='ultra'?'MORE PERSPECTIVES':id.toUpperCase()}</span><h3 class="plan-price">$${plan.pricing.monthlyUsd}<span> / month</span></h3><p>${plan.name} workspace</p><ul><li>${plan.limits.monthlyInputTokens.toLocaleString()} input tokens / month</li><li>${plan.limits.monthlyOutputTokens.toLocaleString()} output tokens / month</li><li>${TEAM_SIZES[id]?`${TEAM_SIZES[id]} collaborating agents with custom jobs`:'Single-model chat'}</li><li>${plan.entitlements.council?'Multi-model Council':'Standard model access'}</li><li>${id==='free'?'$0.10 operator-funded trial':`$${plan.limits.monthlySpendUsd} estimated API budget`}</li>${plan.pricing.studentDiscountPercent?`<li>Verified students: $${plan.pricing.studentMonthlyUsd}/month</li>`:''}</ul><button class="secondary" data-plan="${id}" ${state.status?.billing?.enabled&&id!=='free'?'':'disabled'}>${state.status?.subscription?.planId===id?'Current workspace':state.status?.billing?.enabled?'Test checkout':'Checkout unavailable'}</button>${TEAM_SIZES[id]?`<button class="secondary spaced" data-design-team="${id}">Choose your team’s job ↗</button>`:''}</article>`).join('')}</div><div class="panel spaced"><h3>Student discount</h3><p>${student?.verified?student.checkoutReady?'Verified eligibility found. You can apply 30% off during test checkout.':'Verified eligibility found, but the Stripe student coupon is not configured yet.':'A 30% discount requires an unexpired verification record from the deployment’s trusted verifier. Your request alone never grants eligibility.'}</p>${student?.verified?`<label><input id="student-discount" type="checkbox" ${student.checkoutReady?'':'disabled'}> Apply verified 30% student discount</label>`:''}${!student?.verified?'<button class="secondary" id="request-verification">Verify with SheerID ↗</button><button class="secondary" id="refresh-verification">Refresh verification</button>':''}</div><div class="panel spaced"><h3>Billing management</h3>${state.status?.account?.role==='owner'?'<p><a href="#operations">Webhook operations ↗</a></p>':''}<p>This release supports Stripe Checkout and customer billing management when deployment secrets and price IDs are configured. Provider API keys are still separate from workspace subscription billing.</p>${state.status?.billing?.enabled?'<button class="secondary" id="manage-billing">Manage subscription ↗</button>':''}</div></section>`;
 document.querySelectorAll('[data-design-team]').forEach(button=>button.onclick=()=>chooseTeamPlan(button.dataset.designTeam));
 if($('#request-verification'))$('#request-verification').onclick=async()=>{try{const result=await api('/api/student-verification',{action:'request'});if(result.url){const url=new URL(result.url);if(url.origin!=='https://services.sheerid.com'||!url.pathname.startsWith('/verify/'))throw Error('Invalid verification URL');location.assign(url.href);}else notify(result.message);}catch(err){notify(err.message);}};
 if($('#refresh-verification'))$('#refresh-verification').onclick=async()=>{try{const result=await api('/api/student-verification',{action:'refresh'});notify(result.message);await boot();}catch(err){notify(err.message);}};
 document.querySelectorAll('[data-plan]').forEach(button=>button.onclick=async()=>{const priceId=Object.entries(state.status.billing.prices).find(([,plan])=>plan===button.dataset.plan)?.[0];if(!priceId){notify('No checkout price is configured for this plan.');return;}try{const response=await api('/api/billing/create-checkout',{priceId,studentDiscount:Boolean($('#student-discount')?.checked)});safeBillingRedirect(response.url);}catch(err){notify(err.message);}});
 if($('#manage-billing'))$('#manage-billing').onclick=async()=>{try{safeBillingRedirect((await api('/api/billing/portal',{})).url);}catch(err){notify(err.message);}};
}
function safeBillingRedirect(url){const target=new URL(url);if(target.protocol!=='https:'||!['checkout.stripe.com','billing.stripe.com'].includes(target.hostname))throw new Error('Unexpected billing destination.');location.assign(target.href);}
function renderSettings(){main.innerHTML=`<section class="page">${pageHeader('A workspace that feels like you.','A few useful details about your connection and preferences.')}<div class="panel"><h3>Provider diagnostics</h3><p><a href="#connections">Manage API keys & model combos ↗</a></p><div class="settings-list">${['claude','openai','gemini','grok'].map(id=>{const diag=state.status?.providerDiagnostics?.[id];return `<div class="setting-row"><strong>${symbols[id]} ${id==='openai'?'OpenAI':id[0].toUpperCase()+id.slice(1)}</strong><span>${esc(diag?.message || (connected(id)?'Key configured · access depends on provider':'Not connected'))}</span></div>`;}).join('')}</div><p>Provider keys are configured on the server. Samvit never stores API keys in your browser; invalid-issuer 401s usually mean the deployment is using a key from the wrong provider project or issuer.</p><button class="secondary" id="refresh-connection">Refresh connection ↻</button></div><div class="panel"><h3>Privacy & appearance</h3><p><a href="#account">Password, sessions & account deletion ↗</a></p><p><a href="#appearance">Choose wallpapers, colors & motion ↗</a></p><p>Signed in as ${esc(state.status?.account?.email||'local developer')}. Your conversations, projects, goal plans, memories, and connections belong to your account. Chat content is sent to your selected provider. Fallback is optional.</p><div class="form-row"><button class="secondary" id="settings-theme">Switch theme ◐</button><button class="secondary" id="logout">Sign out</button></div></div></section>`;$('#refresh-connection').onclick=boot;$('#settings-theme').onclick=toggleTheme;$('#logout').onclick=async()=>{try{await api('/api/auth',{logout:true});accountEpoch++;state.abort?.abort();setWorkbenchAccount(null);state.messages=[];state.draft='';state.model='auto';state.conversation=null;state.history=[];$('#history').replaceChildren();await boot();}catch(err){notify(err.message);}};}
async function renderAnalytics(renderId){main.innerHTML=`<section class="page">${pageHeader('A clearer picture of your usage.','A rolling seven-day view from completed provider calls. Costs are estimates, not your provider invoice.')}<div id="analytics-content">${empty('Loading usage…')}</div></section>`;if(!state.status?.authenticated){$('#analytics-content').innerHTML=empty('Connect your workspace to view usage.');return;}try{const result=await api('/api/analytics');if(renderId!==state.renderId)return;const entries=Object.entries(result.usageByProvider);$('#analytics-content').innerHTML=entries.length?`<div class="grid">${entries.map(([id,value])=>`<article class="card"><h3>${esc(id)}</h3><div class="stat">${value.calls}<small> calls</small></div><p>${(value.inputTokens+value.outputTokens).toLocaleString()} tokens</p><p>Estimated cost ${money(value.costUsd)}</p></article>`).join('')}</div>`:empty('No completed model calls yet. Your usage will appear here.');}catch(err){if(renderId===state.renderId)$('#analytics-content').innerHTML=empty(err.message);}}
function toggleTheme(){document.body.classList.toggle('dark');try{localStorage.setItem('samvit-theme',document.body.classList.contains('dark')?'dark':'light');}catch{}}
try{if(localStorage.getItem('samvit-theme')==='dark')document.body.classList.add('dark');}catch{}
$('#theme-toggle').onclick=toggleTheme;
$('#menu-toggle').onclick=()=>{const open=$('#sidebar').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open));};
$('#new-chat').onclick=()=>{if(state.abort||state.saving){notify('Wait for the current response to finish saving.');return;}state.messages=[];state.conversation=null;state.draft='';navigate('chat');};
$('#refresh-history').onclick=refreshHistory;
$('#login-dialog').addEventListener('cancel',event=>event.preventDefault());
let accountAction='signin';
$('#account-mode').onclick=()=>{accountAction=accountAction==='signin'?'register':'signin';$('#invitation-label').hidden=accountAction!=='register';$('#account-mode').textContent=accountAction==='signin'?'Create an account':'Already have an account?';$('#login-form button[type="submit"]').textContent=accountAction==='signin'?'Sign in →':'Create account →';$('#account-password').autocomplete=accountAction==='signin'?'current-password':'new-password';$('#login-error').textContent='';};
$('#explore-demo').onclick=()=>{$('#login-dialog').close();$('#account-password').value='';banner('Interface preview · Sign in to run agents or save work. No AI responses or payments are simulated.');};
$('#login-form').onsubmit=async event=>{event.preventDefault();event.submitter.disabled=true;try{const result=await api('/api/auth',{action:accountAction,email:$('#account-email').value,password:$('#account-password').value,code:$('#access-code').value});$('#access-code').value='';$('#account-password').value='';if(result.accepted){$('#login-error').textContent=result.message;return;}$('#login-dialog').close();await boot();}catch(err){$('#login-error').textContent=err.message;}finally{event.submitter.disabled=false;}};
window.addEventListener('hashchange',render);
window.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key==='k'){event.preventDefault();navigate('chat');$('#prompt')?.focus();}if(event.key==='Escape'){$('#sidebar').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');}});
window.addEventListener('beforeunload',event=>{if(state.abort){event.preventDefault();event.returnValue='';}});
// Voice submits through the SAME goal pipeline as typing, so a spoken
// command inherits identical permissions, confirmations and the kill switch.
function submitSpokenGoal(text,attempt=0){
 if(!text)return;
 location.hash='assistant';
 const form=$('#universal-form'),goal=$('#universal-goal');
 if(form&&goal){goal.value=text;goal.dispatchEvent(new Event('input',{bubbles:true}));form.requestSubmit();return;}
 if(attempt<10)setTimeout(()=>submitSpokenGoal(text,attempt+1),120);
 else notify('Voice command captured, but the goal form is unavailable. Open Ask Samvit and paste it.');
}
initWorkbench({api,notify});initAppearance(notify);
const voice=installVoice({button:$('#voice-toggle'),notify,onCommand:submitSpokenGoal});
globalThis.samvitVoice=voice.engine||null;
if(!voice.supported)notify('Voice input is not supported in this browser.');
render();boot();

async function renderSetup(){main.innerHTML=`<section class="page">${pageHeader('Ready when you are.','Check the connection before you sign in.')}<div id="setup-checks" class="panel">Checking setup…</div></section>`;try{const data=await api('/api/setup');if(!$('#setup-checks'))return;$('#setup-checks').innerHTML=`<h2>${data.ready?'Account setup is ready':'A few setup steps remain'}</h2>${data.checks.map(c=>`<p><strong>${c.ok?'Ready':c.required?'Required':'Optional'} · ${esc(c.key)}</strong><br>${esc(c.message)}</p>`).join('')}<p>${esc(data.demo)}</p><button class="primary" id="setup-signin">Sign in or create account</button>`;$('#setup-signin').onclick=showLogin;}catch{if($('#setup-checks')){$('#setup-checks').innerHTML='<p>The setup check is unavailable. You can still try signing in to your workspace.</p><button class="primary" id="setup-signin" type="button">Sign in or create account</button>';$('#setup-signin').onclick=showLogin;}}}

function renderAccount(){main.innerHTML=`<section class="page">${pageHeader('Your account. Your control.','Manage your password, sessions and account status.')}<form id="security-form" class="panel"><label>Current password<input name="currentPassword" type="password" autocomplete="current-password"></label><label>New password<input name="newPassword" type="password" minlength="12" maxlength="128" autocomplete="new-password"></label><div class="form-row"><button class="primary" name="action" value="password">Change password</button><button class="secondary" name="action" value="signout-all">Sign out everywhere</button><button class="secondary" name="action" value="disable">Disable my account</button></div><p>Disabling immediately revokes sessions. Re-enable through the sign-in form using your credentials.</p><label><input id="confirm-delete" type="checkbox"> I understand deletion removes my account and saved data after a short drain period.</label><button class="secondary" name="action" value="delete">Delete my account</button><p>Active paid subscriptions must end before deletion. Export work you want to keep.</p></form></section>`;$('#security-form').onsubmit=async e=>{e.preventDefault();const action=e.submitter.value;if(action==='delete'&&!$('#confirm-delete').checked){notify('Confirm deletion first.');return;}const body=Object.fromEntries(new FormData(e.target));try{const result=await api('/api/account',{...body,action});e.target.reset();notify(result.message||'Account updated.');if(result.signedOut||result.pending){setWorkbenchAccount(null);state.messages=[];state.history=[];}await boot();}catch(err){notify(err.message);}};}

function renderRecovery(){main.innerHTML=`<section class="page">${pageHeader('Get back to your workspace.','Receive a single-use account link by email.')}<form id="recovery-form" class="panel"><label>Email<input name="email" type="email" required autocomplete="email"></label><label>What do you need?<select name="action"><option value="reset">Reset my password</option><option value="verify">Verify my email</option><option value="enable">Re-enable my account</option></select></label><button class="primary">Request email</button><p id="recovery-message" role="status"></p></form></section>`;$('#recovery-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const result=await api('/api/email',Object.fromEntries(new FormData(e.target)));$('#recovery-message').textContent=result.message;}catch(err){$('#recovery-message').textContent=err.message;}finally{e.submitter.disabled=false;}};}
function renderEmailConfirmation(){const params=new URLSearchParams(location.hash.split('?')[1]||'');main.innerHTML=`<section class="page">${pageHeader('Confirm it’s you.','Choose your password to complete the email request.')}<form id="email-confirm-form" class="panel"><label>New password<input name="newPassword" type="password" required minlength="12" maxlength="128" autocomplete="new-password"></label><button class="primary">Confirm account request</button><p id="email-confirm-message" role="status"></p></form></section>`;$('#email-confirm-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const result=await api('/api/email',{action:'complete',kind:params.get('kind'),token:params.get('token'),newPassword:e.target.elements.newPassword.value});e.target.reset();history.replaceState(null,'',location.pathname+'#recover');notify(result.message);showLogin();}catch(err){$('#email-confirm-message').textContent=err.message;}finally{e.submitter.disabled=false;}};}
$('#account-recovery').onclick=()=>{$('#login-dialog').close();location.hash='recover';};

async function renderOperations(){main.innerHTML=`<section class="page">${pageHeader('Payment operations.','Review failed deliveries and retries.')}<div id="operations-report" class="panel">Loading…</div></section>`;try{const r=await api('/api/billing/operations');if(!$('#operations-report'))return;$('#operations-report').innerHTML=`<p>${esc(r.replay)}</p><p>${r.scanned} events scanned${r.truncated?' · scan limit reached':''}</p>${r.events.map(e=>`<p><strong>${esc(e.eventId)}</strong> · ${esc(e.status)}${e.stale?' · STALE':''} · ${e.attempts} attempt(s)<br>${esc(e.eventType||'Legacy event')} · ${esc(e.at||'')}</p>`).join('')||'<p>No webhook events received yet.</p>'}`;}catch(e){if($('#operations-report'))$('#operations-report').textContent=e.message;}}
