const THEMES=['paper','aurora','dusk','forest','ocean','custom'];
const ACCENTS=['violet','blue','rose','green'];
let preferences={wallpaper:'paper',accent:'violet',motion:true,focus:false};
try{const saved=JSON.parse(localStorage.getItem('samvit-appearance')||'{}');preferences={wallpaper:THEMES.includes(saved.wallpaper)?saved.wallpaper:'paper',accent:ACCENTS.includes(saved.accent)?saved.accent:'violet',motion:saved.motion!==false,focus:saved.focus===true};}catch{}
let image,notify=()=>{};
function apply(){document.body.dataset.wallpaper=preferences.wallpaper;document.body.dataset.accent=preferences.accent;document.body.classList.toggle('motion-off',!preferences.motion);document.body.classList.toggle('focus-mode',preferences.focus);if(image)image.hidden=preferences.wallpaper!=='custom';try{localStorage.setItem('samvit-appearance',JSON.stringify(preferences));}catch{}}
function database(){return new Promise((resolve,reject)=>{const req=indexedDB.open('samvit-personal-workspace',1);req.onupgradeneeded=()=>req.result.createObjectStore('images');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function storedImage(value){const db=await database();try{return await new Promise((resolve,reject)=>{const write=value!==undefined,tx=db.transaction('images',write?'readwrite':'readonly'),store=tx.objectStore('images'),request=write?(value===null?store.delete('wallpaper'):store.put(value,'wallpaper')):store.get('wallpaper');let result;request.onsuccess=()=>result=request.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{db.close();}}
export function initAppearance(toast){notify=toast;image=document.createElement('img');image.id='workspace-wallpaper';image.alt='';image.hidden=true;document.body.prepend(image);apply();storedImage().then(value=>{if(typeof value==='string'&&/^data:image\/(jpeg|png|webp);base64,/.test(value)){image.src=value;apply();}}).catch(()=>{});
 const main=document.querySelector('#main');if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target);}});},{threshold:.06});const seen=new WeakSet();const watch=()=>main.querySelectorAll('.card,.panel,.idea,.job-card,.hero,.page-head').forEach(el=>{if(!seen.has(el)){seen.add(el);el.classList.add('scroll-reveal');observer.observe(el);}});new MutationObserver(records=>{for(const r of records)for(const n of r.removedNodes)if(n.nodeType===1&&!n.isConnected){observer.unobserve(n);n.querySelectorAll('.scroll-reveal').forEach(el=>observer.unobserve(el));}watch();}).observe(main,{childList:true,subtree:true});watch();}
}
export function renderAppearance(){const main=document.querySelector('#main');main.innerHTML=`<section class="page"><div class="page-head"><div><div class="eyebrow">MAKE ROOM FOR YOU</div><h1>Your space. Your atmosphere.</h1><p class="intro">Choose the backdrop, color and pace that help you feel at home with your ideas.</p></div></div><div class="panel"><div class="section-heading"><div><h2>Pick a mood</h2><p>Soft backdrops, with room for your work to breathe.</p></div><span class="tag">SAVED ON THIS DEVICE</span></div><div class="wallpaper-grid">${[['paper','Warm paper','A calm, clean start'],['aurora','Aurora','Soft color, open space'],['dusk','After hours','Warm light, quiet focus'],['forest','Forest light','Fresh space to think'],['ocean','Open water','A clear horizon']].map(([id,label,description])=>`<button class="wallpaper-choice ${preferences.wallpaper===id?'active':''}" data-wallpaper-choice="${id}" aria-pressed="${preferences.wallpaper===id}"><span class="wallpaper-swatch wallpaper-${id}"></span><strong>${label}</strong><small>${description}</small></button>`).join('')}</div></div><div class="panel"><h2>Bring your own wallpaper</h2><p>Choose a JPG, PNG or WebP image up to 5 MB. It stays in this browser and is never sent to a model or uploaded to the server.</p><label class="upload-wallpaper">Choose an image<input id="wallpaper-upload" type="file" accept="image/jpeg,image/png,image/webp"></label><p id="wallpaper-status" role="status">${preferences.wallpaper==='custom'?'Your custom wallpaper is active.':'Make the workspace yours.'}</p><button class="secondary" id="remove-wallpaper">Remove custom wallpaper</button></div><div class="panel"><h2>Find your finishing touches</h2><div class="field-grid"><label>Accent color<select id="accent-color">${ACCENTS.map(a=>`<option value="${a}" ${preferences.accent===a?'selected':''}>${a[0].toUpperCase()+a.slice(1)}</option>`).join('')}</select></label><label class="toggle-setting"><input id="workspace-motion" type="checkbox" ${preferences.motion?'checked':''}> Gentle scrolling animations</label><label class="toggle-setting"><input id="workspace-focus" type="checkbox" ${preferences.focus?'checked':''}> Focus mode · hide suggestions and recent chats</label></div><p>Your device’s reduced-motion preference always takes priority.</p><button class="secondary" id="appearance-theme">Switch light / dark ◐</button></div></section>`;
 document.querySelectorAll('[data-wallpaper-choice]').forEach(b=>b.onclick=()=>{preferences.wallpaper=b.dataset.wallpaperChoice;apply();renderAppearance();});
 document.querySelector('#accent-color').onchange=e=>{preferences.accent=e.target.value;apply();};document.querySelector('#workspace-motion').onchange=e=>{preferences.motion=e.target.checked;apply();};document.querySelector('#workspace-focus').onchange=e=>{preferences.focus=e.target.checked;apply();};document.querySelector('#appearance-theme').onclick=()=>document.querySelector('#theme-toggle').click();
 document.querySelector('#remove-wallpaper').onclick=async()=>{try{await storedImage(null);image.removeAttribute('src');preferences.wallpaper='paper';apply();renderAppearance();notify('Custom wallpaper removed.');}catch{notify('Could not update browser storage.');}};
 document.querySelector('#wallpaper-upload').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const status=document.querySelector('#wallpaper-status');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){status.textContent='Choose a JPG, PNG or WebP image under 5 MB.';e.target.value='';return;}try{status.textContent='Preparing your wallpaper…';const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>40000000){bitmap.close();throw Error('Choose an image under 40 megapixels.');}const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const value=canvas.toDataURL('image/jpeg',.85);await storedImage(value);image.src=value;preferences.wallpaper='custom';apply();status.textContent='Your wallpaper is saved on this device.';notify('Your workspace has a new look.');}catch(err){status.textContent=err.message||'Could not save this image. Try a smaller file.';}finally{e.target.value='';}};
}
