import {priceStatusLabel} from '../shared/pricing-policy.js';
import {TEAM_SIZES,TEAM_JOBS,defaultRoles} from '../shared/teams.js';
import {CONNECTION_PROVIDERS} from '../shared/connections.js';
import {iterateSSE} from '../shared/sse.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s);
const header=(title,description,tag)=>`<div class="page-head"><div><div class="eyebrow">${tag}</div><h1>${title}</h1><p class="intro">${description}</p></div></div>`;
let dependencies,connections={connections:[],combos:[],environmentTargets:[]};
let team={plan:'pro',job:'build',goal:'',agents:[],outputs:[],running:false,abort:null,final:'',message:''};
let currentAccount=null;
export function setWorkbenchAccount(id){if(id===currentAccount)return;team.abort?.abort();currentAccount=id;connections={connections:[],combos:[],environmentTargets:[]};team={plan:'pro',job:'build',goal:'',agents:[],outputs:[],running:false,abort:null,final:'',message:''};if(id)try{const saved=JSON.parse(localStorage.getItem('samvit-team-draft:'+id)||'null');if(saved&&TEAM_SIZES[saved.plan])team={...team,plan:saved.plan,job:TEAM_JOBS.some(j=>j.id===saved.job)?saved.job:'build',goal:String(saved.goal||'').slice(0,6000),agents:Array.isArray(saved.agents)?saved.agents.slice(0,4):[]};}catch{}}
const persistTeam=()=>{if(currentAccount)try{localStorage.setItem('samvit-team-draft:'+currentAccount,JSON.stringify({plan:team.plan,job:team.job,goal:team.goal,agents:team.agents}));}catch{}};
export function initWorkbench(deps){dependencies=deps;window.addEventListener('beforeunload',e=>{if(team.running){e.preventDefault();e.returnValue='';}});}
export const teamRunning=()=>team.running;
export async function refreshConnections(){const account=currentAccount;try{const result=await dependencies.api('/api/connections');if(account!==currentAccount)return connections;connections=result;return connections;}catch{connections={connections:[],combos:[],environmentTargets:[]};return connections;}}
export function routingOptions(){return [...(connections.connections||[]).filter(c=>c.enabled).map(c=>({id:'connection:'+c.id,label:c.name+' · '+c.label})),...(connections.combos||[]).map(c=>({id:'combo:'+c.id,label:c.name+' · combo'}))];}
const allTargets=()=>[...(connections.environmentTargets||[]),...routingOptions()];
export function chooseTeamPlan(plan){if(team.running){dependencies.notify('Stop or finish your current team run first.');return;}team.plan=plan;team.agents=[];persistTeam();location.hash='agents';}
async function manage(body){const code=$('#connection-owner-code')?.value||'';const response=await fetch('/api/connections',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','x-samvit-admin-code':code},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Connection request failed.');return result;}
export async function renderConnections(){
 const main=$('#main');main.innerHTML=`<section class="page">${header('Your models. Connected.','Connect a provider, choose its model, and build a reliable route for your ideas.','CONNECTIONS & COMBOS')}<div class="connection-intro"><span class="orb">↗</span><div><strong>One workspace. More possibilities.</strong><p>Keys are encrypted on the server. These connections are private to your account.</p></div></div><div id="connections-body"><p>Loading connections…</p></div></section>`;
 const data=await refreshConnections();if(!$('#connections-body'))return;
 const content=$('#connections-body');content.innerHTML=`<div class="panel"><h2>Your provider directory</h2><p>Official APIs and an optional OmniRoute gateway. Free allowances have limits; availability depends on the provider account.</p><div class="provider-directory">${CONNECTION_PROVIDERS.map(p=>`<button type="button" class="provider-tile" data-provider="${p.id}"><strong>${esc(p.label)}</strong><small>${esc(p.allowance)}</small></button>`).join('')}</div></div>
 <div class="panel" id="connection-editor"><div class="section-heading"><div><h2>Add or rotate a connection</h2><p>Manage the keys and routing for your own account.</p></div><span class="tag">ENCRYPTED</span></div>${data.managementConfigured?'':'<p class="error">The workspace owner needs to enable secure connection management on the server. Setup steps are in the included README.</p>'}${currentAccount?'':'<label>Development management code<input id="connection-owner-code" type="password" autocomplete="off"></label>'}<form id="connection-form"><input type="hidden" name="id"><div class="field-grid"><label>Provider<select name="provider" id="connection-provider">${CONNECTION_PROVIDERS.map(p=>`<option value="${p.id}">${esc(p.label)}</option>`).join('')}</select></label><label>Connection name<input name="name" required maxlength="60" placeholder="My writing model"></label><label>Model or gateway combo ID<input name="model" id="connection-model" required maxlength="180" placeholder="Exact model ID from your provider"></label><label>API key<input name="apiKey" type="password" required autocomplete="off" placeholder="Paste the matching provider key"></label><label>Estimated input $ / million tokens<input name="input" type="number" min="0" step="any" required value="1"></label><label>Estimated output $ / million tokens<input name="output" type="number" min="0" step="any" required value="5"></label></div><p>Direct-provider catalog rates use a static fallback reviewed 2026-09-14. OpenRouter prices refresh from its live catalog; saved values show their last check below. Custom models need conservative budget estimates. An OmniRoute connection uses the trusted gateway address configured by the operator.</p><div class="form-row"><button class="primary" ${data.managementConfigured?'':'disabled'}>Save encrypted connection</button><button type="reset" class="secondary">Clear form</button></div></form></div>
 <div class="panel"><div class="section-heading"><div><h2>Discover free models</h2><p>Live zero-price OpenRouter text models. Request limits still apply.</p></div><button class="secondary" id="load-free">Refresh catalog ↻</button></div><div id="free-results"><p>Load the live catalog to choose a model.</p></div></div>
 <div class="section-heading"><h2>Your connections</h2><span>${data.connections?.length||0} saved</span></div><div class="grid" id="connection-list">${(data.connections||[]).map(c=>`<article class="card"><div class="card-head"><span class="tag">${esc(c.provider)}</span><span class="health ${c.status==='ready'?'ready':''}">${esc(c.status)}</span></div><h3>${esc(c.name)}</h3><p class="break-word">${esc(c.model)}</p><p>${esc(c.keyHint)} · ${c.verifiedFree?'Verified zero price':'Estimated rates: $'+c.input+' / $'+c.output}</p><p class="rate-age">${esc(priceStatusLabel(c.pricing||{kind:'user-estimate',checkedAt:c.updatedAt}))}</p>${c.cooldownUntil>Date.now()?`<p>Retry after ${esc(new Date(c.cooldownUntil).toLocaleTimeString())}</p>`:''}<div class="form-row"><button class="secondary" data-test="${c.id}">Test model</button><button class="secondary" data-rotate="${c.id}">Rotate key</button><button class="secondary" data-delete="${c.id}">Delete</button></div></article>`).join('')||'<p>No saved connections yet. Environment keys remain available in chat.</p>'}</div>
 <div class="panel spaced"><h2>Build a model combo</h2><p>Choose 2–4 connections. The order below is the fallback order. Responses switch only before text starts.</p><form id="combo-form"><label>Combo name<input name="name" required maxlength="60" placeholder="Everyday creative team"></label><div class="field-grid">${[0,1,2,3].map(i=>`<label>Position ${i+1}${i>1?' · optional':''}<select name="member${i}" ${i<2?'required':''}><option value="">Choose a connection</option>${(data.connections||[]).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label>`).join('')}</div><div class="field-grid"><label>Strategy<select name="strategy"><option value="priority">Priority · start with the first available</option><option value="round-robin">Round robin · rotate the starting connection</option></select></label><label>Spending policy<select name="policy"><option value="free">Free only · verified zero-price models</option><option value="paid">Allow paid usage within workspace budget</option></select></label></div><button class="primary" ${data.managementConfigured?'':'disabled'}>Save combo</button></form></div><div class="grid">${(data.combos||[]).map(c=>`<article class="card"><span class="tag">${c.freeOnly?'FREE ONLY':'PAID ALLOWED'}</span><h3>${esc(c.name)}</h3><p>${esc(c.strategy)}</p><ol>${c.members.map(id=>`<li>${esc(data.connections.find(x=>x.id===id)?.name||'Missing connection')}</li>`).join('')}</ol><button class="secondary" data-delete-combo="${c.id}">Delete combo</button></article>`).join('')}</div><p class="intro spaced">A test sends a small model request and can consume provider credits. Keys and owner codes are never saved to browser storage. Connection prices are rechecked before use where a machine-readable feed is available.</p>`;
 const form=$('#connection-form');
 content.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>{form.elements.provider.value=b.dataset.provider;$('#connection-editor').scrollIntoView({behavior:'smooth',block:'start'});form.elements.name.focus();});
 form.onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const input=Object.fromEntries(new FormData(form));if(!input.id)delete input.id;await manage({action:'save',...input});form.elements.apiKey.value='';dependencies.notify('Connection saved securely.');await renderConnections();}catch(err){dependencies.notify(err.message);}finally{b.disabled=false;}};
 form.onreset=()=>{setTimeout(()=>form.elements.id.value='',0);};
 content.querySelectorAll('[data-rotate]').forEach(b=>b.onclick=()=>{const c=data.connections.find(x=>x.id===b.dataset.rotate);for(const k of ['id','name','provider','model','input','output'])form.elements[k].value=c[k];form.elements.apiKey.value='';form.elements.apiKey.focus();$('#connection-editor').scrollIntoView({block:'start'});});
 for(const [attr,action] of [['test','test'],['delete','delete'],['delete-combo','delete-combo']])content.querySelectorAll(`[data-${attr}]`).forEach(b=>b.onclick=async()=>{b.disabled=true;try{const r=await manage({action,id:b.getAttribute('data-'+attr)});dependencies.notify(r.message||'Removed.');await renderConnections();}catch(err){dependencies.notify(err.message);}finally{b.disabled=false;}});
 $('#combo-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);e.submitter.disabled=true;try{await manage({action:'combo',name:f.get('name'),members:[0,1,2,3].map(i=>f.get('member'+i)).filter(Boolean),strategy:f.get('strategy'),freeOnly:f.get('policy')==='free'});dependencies.notify('Combo saved. Select it in chat or assign it to an agent.');await renderConnections();}catch(err){dependencies.notify(err.message);}finally{e.submitter.disabled=false;}};
 $('#load-free').onclick=async e=>{e.target.disabled=true;const results=$('#free-results');try{const catalog=await dependencies.api('/api/free-models');if(!results.isConnected)return;results.innerHTML=`<p>${catalog.models.length} models · checked ${esc(new Date(catalog.checkedAt).toLocaleString())}</p><label>Find a free model<input id="free-search" type="search" placeholder="Search the live catalog"></label><div class="free-model-list"></div>`;const draw=()=>{const q=$('#free-search').value.toLowerCase();results.querySelector('.free-model-list').innerHTML=catalog.models.filter(m=>(m.label+' '+m.id).toLowerCase().includes(q)).map(m=>`<button class="free-model" data-free="${esc(m.id)}"><strong>${esc(m.label)}</strong><small>${esc(m.id)}</small><span>Use model ↗</span></button>`).join('')||'<p>No matching models.</p>';results.querySelectorAll('[data-free]').forEach(b=>b.onclick=()=>{form.reset();form.elements.provider.value='openrouter';form.elements.model.value=b.dataset.free;form.elements.name.value=catalog.models.find(m=>m.id===b.dataset.free).label.slice(0,60);form.elements.input.value=0;form.elements.output.value=0;$('#connection-editor').scrollIntoView({block:'start'});form.elements.apiKey.focus();});};$('#free-search').oninput=draw;draw();}catch(err){results.textContent=err.message;}finally{e.target.disabled=false;}};
}
export async function renderTeams(){
 const renderAccount=currentAccount;
 const main=$('#main');main.innerHTML=`<section class="page">${header('One goal. Your AI team.','Assign the roles. Pass the work forward. Bring it together in one final answer.','AGENT STUDIO')}<div class="panel budget-trust"><strong>Ambitious work. A budget you control.</strong><p>Samvit reserves your account’s estimated allowance before each model call. Concurrent requests share that limit, and interrupted calls retain a conservative charge. Estimates depend on provider rates and reported usage; they are not a guarantee of your provider invoice.</p><p>Choose roles below, connect your models, then run your team. Stop at any time and export the contributions.</p></div><div id="team-body">Loading your team…</div></section>`;
 await refreshConnections();let subscription=null;try{subscription=(await dependencies.api('/api/billing/status')).subscription;}catch{}
 if(renderAccount!==currentAccount||!$('#team-body'))return;
 const entitled=subscription?.status==='active'?TEAM_SIZES[subscription.planId]||0:0;
 // Saved plan selection is a preview only. Authorization always comes from the server.
 if(!TEAM_SIZES[team.plan])team.plan=entitled?subscription.planId:'pro';
 const count=TEAM_SIZES[team.plan],targets=allTargets();
 if(team.agents.length!==count)team.agents=defaultRoles(team.job,count).map((role,i)=>({role,target:targets[i%Math.max(1,targets.length)]?.id||''}));
 const enabled=entitled===count;
 $('#team-body').innerHTML=`<div class="team-plan-tabs" aria-label="Preview team size">${['pro','ultra','ultimate'].map(p=>`<button class="team-plan ${p===team.plan?'active':''}" data-team-plan="${p}" aria-pressed="${p===team.plan}" ${team.running?'disabled':''}><strong>${p[0].toUpperCase()+p.slice(1)}</strong><span>${TEAM_SIZES[p]} agents</span></button>`).join('')}</div>${enabled?'':`<p class="preview-note">You’re designing a ${team.plan} team. Running it requires an active ${team.plan} subscription. <a href="#plans">View billing plans ↗</a></p>`}
 <div class="section-heading"><h2>What should your team do?</h2><span>01 / CHOOSE A JOB</span></div><div class="job-grid">${TEAM_JOBS.map(j=>`<button class="job-card ${j.id===team.job?'active':''}" data-job="${j.id}" aria-pressed="${j.id===team.job}" ${team.running?'disabled':''}><strong>${esc(j.label)}</strong><small>${esc(j.description)}</small></button>`).join('')}</div>
 <form id="team-form"><div class="panel spaced"><label>Your team’s goal<textarea id="team-goal" maxlength="6000" rows="3" required ${team.running?'disabled':''} placeholder="Describe the outcome you want, and any constraints…">${esc(team.goal)}</textarea></label></div><div class="section-heading"><h2>Meet your team</h2><span>02 / ASSIGN EACH ROLE</span></div><div class="agent-grid">${team.agents.map((a,i)=>`<article class="card agent-card"><div class="agent-top"><span class="agent-avatar">${i+1}</span><div><h3>Agent ${i+1}</h3><small>${i===count-1?'Final answer & synthesis':i===0?'Starts the work':'Builds on previous agents'}</small></div></div><label>Model or combo<select name="target${i}" required ${team.running?'disabled':''}><option value="">Choose a connected model</option>${targets.map(t=>`<option value="${esc(t.id)}" ${a.target===t.id?'selected':''}>${esc(t.label)}</option>`).join('')}</select></label><label>Particular job<textarea name="role${i}" required maxlength="1000" rows="4" ${team.running?'disabled':''}>${esc(a.role)}</textarea></label></article>`).join('')}</div><div class="team-run-bar"><div><strong>${count} agents. One shared goal.</strong><small>Each handoff consumes tokens. All calls use your workspace budget.</small></div><button class="primary" id="run-team" ${!enabled||team.running||!targets.length?'disabled':''}>Run team ↗</button><button class="secondary" type="button" id="stop-team" ${team.running?'':'hidden'}>Stop run ■</button></div>${!targets.length?'<p>Connect a model in <a href="#connections">Connections</a> to start.</p>':''}</form>
 <div class="section-heading"><h2>The collaboration</h2><button class="secondary" id="export-team" ${team.outputs.length?'':'disabled'}>Export run ↗</button></div><p id="team-status" role="status">${esc(team.message||'Your agents’ contributions will appear here.')}</p><div id="team-results" class="team-results"></div>`;
 drawOutputs();
 document.querySelectorAll('[data-team-plan]').forEach(b=>b.onclick=()=>{team.plan=b.dataset.teamPlan;team.agents=[];persistTeam();renderTeams();});
 document.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>{team.job=b.dataset.job;const roles=defaultRoles(team.job,count);team.agents=team.agents.map((a,i)=>({...a,role:roles[i]}));persistTeam();renderTeams();});
 $('#team-goal').oninput=e=>{team.goal=e.target.value;persistTeam();};
 team.agents.forEach((a,i)=>{const f=$('#team-form');f.elements['target'+i].onchange=e=>{a.target=e.target.value;persistTeam();};f.elements['role'+i].oninput=e=>{a.role=e.target.value;persistTeam();};});
 $('#stop-team').onclick=()=>team.abort?.abort();$('#export-team').onclick=exportTeam;
 $('#team-form').onsubmit=async e=>{e.preventDefault();if(team.running)return;const runAccount=currentAccount;team.running=true;team.abort=new AbortController();team.runGoal=team.goal;team.outputs=team.agents.map(a=>({text:'',state:'Waiting',model:'',role:a.role}));team.final='';team.message='Starting your team…';await renderTeams();
 if(runAccount!==currentAccount)return;
 try{const response=await dependencies.api('/api/agents',{goal:team.goal,agents:team.agents},'POST',team.abort.signal);let terminal=false;
  for await(const {data} of iterateSSE(response)){if(runAccount!==currentAccount)return;const event=JSON.parse(data);if(event.agentStart!==undefined){team.outputs[event.agentStart].state='Working';team.message=`Agent ${event.agentStart+1} is working…`;}
   if(event.selected&&team.outputs[event.agent])team.outputs[event.agent].model=event.name||event.model;
   if(event.delta&&team.outputs[event.agent])team.outputs[event.agent].text+=event.delta;
   if(event.agentDone!==undefined)team.outputs[event.agentDone].state='Complete';
   if(event.skipped)team.message=`${event.name}: ${event.reason}. Checking the next connection…`;
   if(event.error)throw new Error(event.error);
   if(event.done){terminal=true;team.final=event.final;team.message='Team complete. Your final answer is in the last contribution.';}
   drawOutputs();
  }
  if(!terminal)throw new Error('The team stream ended early.');
 }catch(err){if(runAccount!==currentAccount)return;team.message=err.name==='AbortError'?'Run stopped. Partial contributions are preserved.':err.message;team.outputs.forEach(o=>{if(o.state==='Working')o.state='Partial';});}finally{if(runAccount!==currentAccount)return;team.running=false;team.abort=null;if(location.hash==='#agents')await renderTeams();else dependencies.notify(team.message);}};
}
function drawOutputs(){const result=$('#team-results');if(!result)return;
 while(result.children.length>team.outputs.length)result.lastElementChild.remove();
 team.outputs.forEach((o,i)=>{let card=result.children[i];if(!card){card=document.createElement('article');card.className='panel contribution';const h=document.createElement('h3'),p=document.createElement('div');p.className='contribution-text';card.append(h,p);result.append(card);}card.firstElementChild.textContent=`Agent ${i+1} · ${o.state}${o.model?' · '+o.model:''}`;card.lastElementChild.textContent=o.text||'Waiting for the previous contribution…';});
 if($('#team-status'))$('#team-status').textContent=team.message;if($('#export-team'))$('#export-team').disabled=!team.outputs.length;
}
function exportTeam(){const text=`Goal: ${team.runGoal||team.goal}\n\n`+team.outputs.map((o,i)=>`Agent ${i+1}: ${o.role}\nModel: ${o.model}\nStatus: ${o.state}\n\n${o.text}`).join('\n\n---\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download='samvit-team-run.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
